// ============================================================
// RECOMP — Données : programme, recettes, badges, tips
// (la bibliothèque d'exercices vit dans exercises.js,
//  la base de connaissances du coach dans knowledge.js)
// ============================================================

// --- Programme par défaut ----------------------------------------------------
// Chaque exercice référence un id de la bibliothèque (EXLIB) + sa prescription.
window.DEFAULT_PROGRAM = {
  name: 'Recomposition 4 semaines',
  weeks: 4,
  note: "Surcharge progressive : +1 rép par série à RPE constant chaque semaine, puis +charge quand le haut de fourchette est atteint.",
  sessions: [
    {
      id: 'A', name: 'Séance A', sub: 'Bas du corps & abdos', emoji: '🦵',
      exercises: [
        { exo: 'goblet-squat',   sets: 4, reps: '10–12',   tempo: '3010', rest: 90,  rpe: '7–8' },
        { exo: 'rear-lunge',     sets: 3, reps: '10/jambe', tempo: '2010', rest: 90,  rpe: '7'   },
        { exo: 'romanian-dl',    sets: 4, reps: '10',      tempo: '3110', rest: 90,  rpe: '7–8' },
        { exo: 'back-ext',       sets: 3, reps: '12–15',   tempo: '2012', rest: 60,  rpe: '7'   },
        { exo: 'leg-raise',      sets: 3, reps: '12–15',   tempo: '2011', rest: 60,  rpe: '7–8' },
        { exo: 'calf-raise',     sets: 4, reps: '15–20',   tempo: '2011', rest: 45,  rpe: '8'   }
      ]
    },
    {
      id: 'B', name: 'Séance B', sub: 'Haut du corps & dos', emoji: '💪',
      exercises: [
        { exo: 'pullup-neutral', sets: 4, reps: 'max 6–10', tempo: '2011', rest: 120, rpe: '8'   },
        { exo: 'db-row',         sets: 4, reps: '10–12/bras', tempo: '2011', rest: 90, rpe: '7–8' },
        { exo: 'dips-partial',   sets: 3, reps: '8–10',    tempo: '2010', rest: 90,  rpe: '6–7' },
        { exo: 'db-curl',        sets: 3, reps: '10–12',   tempo: '2011', rest: 60,  rpe: '8'   },
        { exo: 'shrugs',         sets: 3, reps: '12–15',   tempo: '2011', rest: 60,  rpe: '7'   },
        { exo: 'plank',          sets: 3, reps: '45–60 s', tempo: '—',    rest: 60,  rpe: '7'   }
      ]
    }
  ]
};

// --- Recettes ------------------------------------------------------------------
// micros = points forts micronutritionnels · tags = labels rapides (protéines, vegan…)
// tip = astuce du chef (nutrition/technique) · cost = €/portion · time = minutes
// batch = adapté au batch cooking. Le filtrage par exclusion (œufs, lactose, vegan…)
// est géré dynamiquement par allowedRecipes() dans app.js selon le profil.
window.RECIPES = [
  // ---------- PETIT-DÉJ ----------
  { id: 'r-skyr-bowl', name: 'Bowl skyr, flocons & banane', meal: 'petit-déj', kcal: 430, p: 32, c: 55, f: 9, time: 5, cost: 1.6,
    micros: ['Calcium', 'Potassium', 'B12'],
    ing: [['Skyr nature', 250, 'Frais'], ["Flocons d'avoine", 50, 'Épicerie'], ['Banane', 120, 'Fruits'], ['Beurre de cacahuète', 10, 'Épicerie']],
    steps: "Mélange skyr et flocons, laisse gonfler 5 min. Banane en rondelles, filet de beurre de cacahuète." },
  { id: 'r-porridge', name: 'Porridge protéiné fruits rouges', meal: 'petit-déj', kcal: 420, p: 34, c: 50, f: 8, time: 7, cost: 1.8,
    micros: ['Fibres', 'Antioxydants', 'Manganèse'],
    ing: [["Flocons d'avoine", 60, 'Épicerie'], ['Whey vanille', 30, 'Épicerie'], ['Fruits rouges surgelés', 100, 'Surgelés'], ['Lait demi-écrémé', 150, 'Frais']],
    steps: "Flocons + lait 2 min au micro-ondes. Hors chauffe, incorpore la whey (sinon elle coagule). Fruits rouges réchauffés dessus." },
  { id: 'r-overnight', name: 'Overnight oats choco-noisette', meal: 'petit-déj', kcal: 450, p: 28, c: 58, f: 12, time: 5, cost: 1.5, batch: true,
    batchNote: "Prépare 3 bocaux d'un coup : se conserve 3 jours au frigo.",
    micros: ['Magnésium', 'Fibres', 'Fer'],
    ing: [["Flocons d'avoine", 60, 'Épicerie'], ['Fromage blanc 3%', 150, 'Frais'], ['Lait demi-écrémé', 100, 'Frais'], ['Cacao non sucré', 8, 'Épicerie'], ['Noisettes', 12, 'Épicerie'], ['Miel', 10, 'Épicerie']],
    steps: "Mélange tout dans un bocal la veille. Le matin : prêt. Noisettes concassées au moment de servir." },
  { id: 'r-galettes', name: "Galettes d'avoine à la banane (sans œuf)", meal: 'petit-déj', kcal: 390, p: 22, c: 60, f: 8, time: 12, cost: 1.2,
    micros: ['Potassium', 'Fibres'],
    ing: [["Flocons d'avoine", 70, 'Épicerie'], ['Banane bien mûre', 130, 'Fruits'], ['Whey vanille', 20, 'Épicerie'], ['Lait demi-écrémé', 60, 'Frais']],
    steps: "Écrase la banane (c'est elle qui lie, pas besoin d'œuf), mélange tout. Poêle anti-adhésive feu moyen, 2 min par face." },
  { id: 'r-smoothie', name: 'Smoothie banane-beurre de cacahuète', meal: 'petit-déj', kcal: 410, p: 30, c: 45, f: 12, time: 3, cost: 1.4,
    micros: ['Potassium', 'Magnésium', 'B12'],
    ing: [['Lait demi-écrémé', 250, 'Frais'], ['Banane', 100, 'Fruits'], ['Whey vanille', 30, 'Épicerie'], ['Beurre de cacahuète', 12, 'Épicerie']],
    steps: "Tout au blender 30 s. Idéal les matins pressés ou en post-séance." },
  // ---------- DÉJEUNER ----------
  { id: 'r-poulet-riz', name: 'Poulet, riz & brocoli', meal: 'déjeuner', kcal: 520, p: 45, c: 55, f: 11, time: 20, cost: 2.8, batch: true,
    batchNote: "Le classique du meal prep : cuis 600 g de poulet et 280 g de riz d'un coup = 4 boîtes.",
    micros: ['Vitamine C', 'B6', 'Sélénium'],
    ing: [['Filet de poulet', 150, 'Boucherie'], ['Riz basmati (cru)', 70, 'Épicerie'], ['Brocoli', 200, 'Légumes'], ["Huile d'olive", 10, 'Épicerie'], ['Paprika', 2, 'Épicerie'], ['Ail en poudre', 2, 'Épicerie']],
    steps: "Cuis le riz. Saisis le poulet en dés 6–8 min (paprika, ail en poudre). Brocoli vapeur 5 min — encore croquant pour garder la vitamine C. Huile d'olive en finition." },
  { id: 'r-pates-thon', name: 'Pâtes au thon & tomate', meal: 'déjeuner', kcal: 530, p: 38, c: 65, f: 11, time: 15, cost: 2.2,
    micros: ['Oméga-3', 'Lycopène', 'Iode'],
    ing: [['Pâtes complètes (crues)', 80, 'Épicerie'], ['Thon au naturel', 140, 'Conserves'], ['Coulis de tomate', 200, 'Conserves'], ["Huile d'olive", 8, 'Épicerie'], ['Ail', 5, 'Légumes'], ['Origan', 2, 'Épicerie']],
    steps: "Pâtes al dente. Chauffe le coulis avec ail et origan, ajoute le thon égoutté 2 min. Le lycopène de la tomate cuite est mieux absorbé avec un filet d'huile." },
  { id: 'r-wrap-poulet', name: 'Wrap poulet crudités', meal: 'déjeuner', kcal: 480, p: 38, c: 45, f: 15, time: 10, cost: 2.5,
    micros: ['Bêta-carotène', 'Fibres'],
    ing: [['Tortilla de blé', 70, 'Épicerie'], ['Filet de poulet', 120, 'Boucherie'], ['Carotte râpée', 60, 'Légumes'], ['Concombre', 60, 'Légumes'], ['Fromage blanc 3%', 40, 'Frais'], ['Citron', 10, 'Fruits']],
    steps: "Poulet grillé en lamelles. Tartine la tortilla de fromage blanc citronné, garnis, roule serré. Transportable partout." },
  { id: 'r-quinoa-bowl', name: 'Bowl quinoa, poulet & avocat', meal: 'déjeuner', kcal: 560, p: 40, c: 48, f: 20, time: 20, cost: 3.2,
    micros: ['Folates', 'Vitamine E', 'Magnésium'],
    ing: [['Quinoa (cru)', 70, 'Épicerie'], ['Filet de poulet', 130, 'Boucherie'], ['Avocat', 70, 'Fruits'], ['Tomates cerises', 100, 'Légumes'], ['Citron', 20, 'Fruits']],
    steps: "Quinoa 12 min à l'eau salée. Poulet grillé. Assemble avec avocat en dés, tomates, jus de citron. Protéine complète + bons lipides." },
  { id: 'r-salade-riz', name: 'Salade de riz thon-maïs', meal: 'déjeuner', kcal: 490, p: 32, c: 62, f: 12, time: 15, cost: 2.0, batch: true,
    batchNote: "Se prépare en saladier pour 3 portions, 3 jours au frigo.",
    micros: ['Iode', 'Sélénium'],
    ing: [['Riz (cru)', 70, 'Épicerie'], ['Thon au naturel', 120, 'Conserves'], ['Maïs', 80, 'Conserves'], ['Tomate', 100, 'Légumes'], ["Huile d'olive", 10, 'Épicerie']],
    steps: "Riz refroidi + thon + maïs + tomate en dés. Vinaigrette légère. Le riz refroidi forme de l'amidon résistant : meilleur pour la satiété." },
  { id: 'r-tartines', name: 'Tartines complètes thon-avocat', meal: 'déjeuner', kcal: 470, p: 30, c: 42, f: 19, time: 8, cost: 2.6,
    micros: ['Oméga-3', 'Vitamine E', 'Fibres'],
    ing: [['Pain complet', 90, 'Boulangerie'], ['Thon au naturel', 100, 'Conserves'], ['Avocat', 80, 'Fruits'], ['Citron', 15, 'Fruits'], ['Poivre', 1, 'Épicerie'], ["Piment d'Espelette", 1, 'Épicerie']],
    steps: "Écrase l'avocat au citron, étale, ajoute le thon émietté. Poivre, piment d'Espelette. Déjeuner express." },
  // ---------- DÎNER ----------
  { id: 'r-boeuf-patate', name: 'Bœuf 5 %, patate douce & haricots', meal: 'dîner', kcal: 540, p: 42, c: 50, f: 14, time: 30, cost: 3.0, batch: true,
    batchNote: "Rôtis 1 kg de patates douces d'un coup : elles se réchauffent parfaitement.",
    micros: ['Fer héminique', 'Bêta-carotène', 'Zinc'],
    ing: [['Steak haché 5%', 150, 'Boucherie'], ['Patate douce', 250, 'Légumes'], ['Haricots verts', 200, 'Légumes'], ["Huile d'olive", 8, 'Épicerie']],
    steps: "Patate douce en cubes au four 25 min à 200 °C. Steak à la poêle. Haricots vapeur 8 min. Le fer du bœuf est le mieux absorbé de tous." },
  { id: 'r-dahl', name: 'Dahl de lentilles corail', meal: 'dîner', kcal: 510, p: 26, c: 75, f: 10, time: 20, cost: 1.5, batch: true,
    batchNote: "×3 sans effort : le dahl est encore meilleur réchauffé le lendemain.",
    micros: ['Fer', 'Folates', 'Fibres'],
    ing: [['Lentilles corail (crues)', 90, 'Épicerie'], ['Riz basmati (cru)', 50, 'Épicerie'], ['Lait de coco léger', 100, 'Conserves'], ['Tomates concassées', 150, 'Conserves'], ['Curry + curcuma', 5, 'Épicerie']],
    steps: "Lentilles + tomates + épices + 250 ml d'eau, 15 min feu doux. Lait de coco en fin. Sers sur riz. Le repas le moins cher de l'app." },
  { id: 'r-sardines', name: 'Sardines, pommes de terre & courgettes', meal: 'dîner', kcal: 500, p: 34, c: 45, f: 19, time: 20, cost: 2.4,
    micros: ['Oméga-3 EPA/DHA', 'Calcium', 'Vitamine D'],
    ing: [["Sardines à l'huile (égouttées)", 100, 'Conserves'], ['Pommes de terre', 300, 'Légumes'], ['Courgette', 200, 'Légumes'], ['Citron', 30, 'Fruits'], ['Persil', 5, 'Légumes']],
    steps: "Pommes de terre vapeur 15 min, courgettes poêlées 6 min. Sardines tièdes dessus, citron, persil. Avec les arêtes = la meilleure source de calcium qui existe." },
  { id: 'r-chili', name: 'Chili express bœuf-haricots', meal: 'dîner', kcal: 560, p: 44, c: 55, f: 15, time: 20, cost: 2.7, batch: true,
    batchNote: "LA recette à tripler : congèle en portions, dépanne n'importe quel soir.",
    micros: ['Fer', 'Fibres', 'Zinc'],
    ing: [['Steak haché 5%', 130, 'Boucherie'], ['Haricots rouges (égouttés)', 130, 'Conserves'], ['Tomates concassées', 200, 'Conserves'], ['Riz (cru)', 50, 'Épicerie'], ['Paprika fumé + cumin', 5, 'Épicerie']],
    steps: "Saisis la viande, ajoute tomates + haricots + épices, mijote 10 min. Sers sur riz." },
  { id: 'r-curry-poulet', name: 'Curry de poulet coco-riz', meal: 'dîner', kcal: 570, p: 42, c: 58, f: 16, time: 25, cost: 3.0, batch: true,
    batchNote: "Double les quantités : le curry se bonifie au frigo.",
    micros: ['B6', 'Sélénium', 'Curcumine'],
    ing: [['Filet de poulet', 150, 'Boucherie'], ['Riz basmati (cru)', 65, 'Épicerie'], ['Lait de coco léger', 120, 'Conserves'], ['Courgette', 150, 'Légumes'], ['Curry', 6, 'Épicerie'], ['Poivre noir', 2, 'Épicerie']],
    steps: "Poulet saisi, courgette en dés 3 min, lait de coco + curry, mijote 10 min. Sur riz. Le curcuma du curry + poivre noir = duo anti-inflammatoire." },
  { id: 'r-saumon', name: 'Saumon, riz & épinards', meal: 'dîner', kcal: 580, p: 38, c: 50, f: 22, time: 18, cost: 4.2,
    micros: ['Oméga-3 EPA/DHA', 'Vitamine D', 'Fer'],
    ing: [['Pavé de saumon', 140, 'Poissonnerie'], ['Riz (cru)', 65, 'Épicerie'], ['Épinards frais', 150, 'Légumes'], ['Citron', 20, 'Fruits'], ['Ail', 5, 'Légumes']],
    steps: "Saumon au four 12 min à 200 °C (ou poêle côté peau). Épinards tombés 2 min à l'ail. 2 poissons gras/semaine = la cible oméga-3." },
  { id: 'r-boeuf-brocoli', name: 'Bœuf sauté au brocoli (façon asiatique)', meal: 'dîner', kcal: 520, p: 40, c: 48, f: 16, time: 15, cost: 3.4,
    micros: ['Fer', 'Vitamine C', 'Zinc'],
    ing: [['Bœuf à sauter (rumsteck)', 140, 'Boucherie'], ['Brocoli', 200, 'Légumes'], ['Riz (cru)', 60, 'Épicerie'], ['Sauce soja', 15, 'Épicerie'], ['Ail + gingembre', 8, 'Légumes']],
    steps: "Wok très chaud : bœuf en lamelles 2 min, réserve. Brocoli 4 min avec un fond d'eau. Réunis avec soja-ail-gingembre. La vitamine C du brocoli booste l'absorption du fer." },
  { id: 'r-dinde-pates', name: 'Pâtes à la dinde hachée & courgettes', meal: 'dîner', kcal: 540, p: 44, c: 60, f: 11, time: 18, cost: 2.8, batch: true,
    batchNote: "La sauce se congèle très bien en portions.",
    micros: ['B3', 'Sélénium', 'Lycopène'],
    ing: [['Dinde hachée', 150, 'Boucherie'], ['Pâtes complètes (crues)', 75, 'Épicerie'], ['Coulis de tomate', 180, 'Conserves'], ['Courgette', 150, 'Légumes'], ['Ail', 5, 'Légumes']],
    steps: "Dinde revenue à l'ail, courgette râpée (invisible dans la sauce !), coulis, 8 min. La dinde : aussi protéinée que le poulet, souvent moins chère." },
  { id: 'r-tofu', name: 'Tofu sauté, riz & légumes (végé)', meal: 'dîner', kcal: 490, p: 28, c: 58, f: 15, time: 18, cost: 2.3,
    micros: ['Calcium', 'Fer', 'Isoflavones'],
    ing: [['Tofu ferme', 180, 'Frais'], ['Riz (cru)', 60, 'Épicerie'], ['Poivron', 120, 'Légumes'], ['Sauce soja', 15, 'Épicerie'], ['Huile de sésame', 8, 'Épicerie']],
    steps: "Tofu pressé puis doré 6 min (il doit croustiller). Poivron sauté. Soja + sésame en finition. Option végé complète de l'app." },
  { id: 'r-soupe-lentilles', name: 'Soupe complète lentilles-carottes', meal: 'dîner', kcal: 430, p: 24, c: 60, f: 9, time: 25, cost: 1.4, batch: true,
    batchNote: "Une marmite = 4 dîners. Se congèle parfaitement.",
    micros: ['Fer', 'Bêta-carotène', 'Fibres'],
    ing: [['Lentilles vertes (crues)', 80, 'Épicerie'], ['Carottes', 200, 'Légumes'], ['Pommes de terre', 150, 'Légumes'], ['Bouillon de légumes', 500, 'Épicerie'], ['Cumin', 3, 'Épicerie']],
    steps: "Tout dans la marmite, 25 min. Mixe la moitié pour le velouté, garde l'autre pour la mâche. Rassasiant pour très peu de calories." },
  // ---------- COLLATIONS ----------
  { id: 'r-fb-miel', name: 'Fromage blanc, miel & amandes', meal: 'collation', kcal: 280, p: 22, c: 24, f: 11, time: 2, cost: 1.1,
    micros: ['Calcium', 'Caséine lente', 'Vitamine E'],
    ing: [['Fromage blanc 3%', 250, 'Frais'], ['Miel', 15, 'Épicerie'], ['Amandes', 15, 'Épicerie']],
    steps: "Assemble. La caséine du fromage blanc se digère en 6–7 h : la collation parfaite du soir pour nourrir le muscle pendant la nuit." },
  { id: 'r-yaourt-granola', name: 'Yaourt grec, granola & kiwi', meal: 'collation', kcal: 290, p: 18, c: 32, f: 10, time: 3, cost: 1.5,
    micros: ['Vitamine C', 'Probiotiques', 'Calcium'],
    ing: [['Yaourt grec', 170, 'Frais'], ['Granola', 30, 'Épicerie'], ['Kiwi', 90, 'Fruits']],
    steps: "Assemble. 1 kiwi = 100 % de la vitamine C journalière. Les probiotiques du yaourt soutiennent la digestion des protéines." },
  { id: 'r-riz-au-lait', name: 'Riz au lait protéiné vanille', meal: 'collation', kcal: 310, p: 24, c: 45, f: 5, time: 25, cost: 1.2, batch: true,
    batchNote: "Prépare 4 pots d'un coup, 4 jours au frigo. Le dessert qui rentre dans les macros.",
    micros: ['Calcium', 'B12'],
    ing: [['Riz rond (cru)', 50, 'Épicerie'], ['Lait demi-écrémé', 300, 'Frais'], ['Whey vanille', 25, 'Épicerie'], ['Cannelle', 2, 'Épicerie']],
    steps: "Riz dans le lait à feu doux 25 min en remuant. Hors du feu, attends 5 min puis incorpore la whey (jamais sur le feu)." },
  { id: 'r-pois-chiches', name: 'Pois chiches rôtis croustillants', meal: 'collation', kcal: 250, p: 13, c: 35, f: 7, time: 30, cost: 0.8, batch: true,
    batchNote: "Une plaque entière se garde 4 jours en boîte hermétique : le snack salé anti-chips.",
    micros: ['Fibres', 'Fer', 'Folates'],
    ing: [['Pois chiches (égouttés)', 150, 'Conserves'], ["Huile d'olive", 6, 'Épicerie'], ['Paprika fumé', 3, 'Épicerie']],
    steps: "Sèche bien les pois chiches, huile + épices, four 200 °C 25–30 min en secouant à mi-cuisson. Croustillant garanti." },

  // ---------- PETIT-DÉJ (compléments) ----------
  { id: 'r-tartine-rc', name: 'Tartine ricotta, miel & noix', meal: 'petit-déj', kcal: 380, p: 18, c: 48, f: 14, time: 5, cost: 2.0,
    micros: ['Calcium', 'Oméga-3 ALA', 'Manganèse'],
    ing: [['Pain complet', 80, 'Boulangerie'], ['Ricotta', 60, 'Frais'], ['Miel', 12, 'Épicerie'], ['Cerneaux de noix', 15, 'Épicerie']],
    steps: "Tartine la ricotta sur le pain toasté. Filet de miel, noix concassées. Ratio protéines/glucides idéal pour démarrer sans lourdeur." },
  { id: 'r-chia-pudding', name: 'Chia pudding coco-mangue', meal: 'petit-déj', kcal: 360, p: 14, c: 42, f: 14, time: 5, cost: 1.8, batch: true,
    batchNote: "Prépare 3 bocaux la veille : 3 matins réglés.",
    micros: ['Oméga-3 ALA', 'Fibres', 'Vitamine C'],
    ing: [['Graines de chia', 30, 'Épicerie'], ['Lait de coco léger', 200, 'Conserves'], ['Mangue surgelée', 100, 'Surgelés'], ['Miel', 10, 'Épicerie']],
    steps: "Mélange chia + lait de coco + miel. Frigo 4 h minimum (ou toute la nuit). Mangue décongelée en dés dessus le matin." },

  // ---------- DÉJEUNER (compléments) ----------
  { id: 'r-buddha-bowl', name: 'Buddha bowl complet', meal: 'déjeuner', kcal: 550, p: 28, c: 62, f: 18, time: 20, cost: 3.0,
    micros: ['Fibres', 'Fer', 'Vitamine C'],
    ing: [['Quinoa (cru)', 60, 'Épicerie'], ['Pois chiches (égouttées)', 100, 'Conserves'], ['Patate douce', 150, 'Légumes'], ['Avocat', 60, 'Fruits'], ['Épinards frais', 50, 'Légumes'], ['Tahini', 15, 'Épicerie'], ['Citron', 15, 'Fruits']],
    steps: "Quinoa 12 min. Patate douce en cubes rôtis au four 20 min. Assemble tout dans un bol : quinoa, pois chiches, patate douce, avocat, épinards. Sauce tahini + citron." },
  { id: 'r-poke', name: 'Poké bowl saumon-riz', meal: 'déjeuner', kcal: 520, p: 32, c: 55, f: 16, time: 15, cost: 4.5,
    micros: ['Oméga-3 EPA/DHA', 'Sélénium', 'Iode'],
    ing: [['Saumon frais (sushi grade)', 120, 'Poissonnerie'], ['Riz (cru)', 65, 'Épicerie'], ['Concombre', 80, 'Légumes'], ['Avocat', 50, 'Fruits'], ['Sauce soja', 15, 'Épicerie'], ['Graines de sésame', 5, 'Épicerie'], ['Vinaigre de riz', 10, 'Épicerie']],
    steps: "Riz vinaigré refroidi. Saumon en cubes marinés 10 min dans soja + sésame. Concombre et avocat en lamelles. Assemble froid." },
  { id: 'r-gratin-patate', name: 'Gratin de patate douce au poulet', meal: 'déjeuner', kcal: 540, p: 42, c: 50, f: 14, time: 35, cost: 3.2, batch: true,
    batchNote: "Un plat pour 4 portions : découpe et congèle.",
    micros: ['Bêta-carotène', 'B6', 'Sélénium'],
    ing: [['Filet de poulet', 150, 'Boucherie'], ['Patate douce', 300, 'Légumes'], ['Fromage râpé', 25, 'Frais'], ['Crème légère 15%', 50, 'Frais'], ['Moutarde', 5, 'Épicerie']],
    steps: "Patate douce en rondelles, poulet en morceaux. Couches alternées dans un plat. Crème + moutarde + fromage dessus. Four 30 min à 180 °C." },
  { id: 'r-taboulé', name: 'Taboulé de boulgour aux herbes', meal: 'déjeuner', kcal: 430, p: 12, c: 58, f: 16, time: 15, cost: 1.8, batch: true,
    batchNote: "Se conserve 3 jours au frigo. Idéal pour les lunchbox.",
    micros: ['Fibres', 'Fer', 'Vitamine C'],
    ing: [['Boulgour (cru)', 80, 'Épicerie'], ['Tomates', 150, 'Légumes'], ['Concombre', 100, 'Légumes'], ['Menthe fraîche', 10, 'Légumes'], ['Persil plat', 20, 'Légumes'], ['Huile d olive', 15, 'Épicerie'], ['Citron', 30, 'Fruits']],
    steps: "Boulgour couvert d'eau bouillante 10 min, égoutter. Tomates et concombre en petits dés. Herbes ciselées. Assaisonne huile + citron. Sers frais." },

  // ---------- DÎNER (compléments) ----------
  { id: 'r-ratatouille', name: 'Ratatouille & steak haché', meal: 'dîner', kcal: 480, p: 36, c: 35, f: 18, time: 30, cost: 3.0, batch: true,
    batchNote: "La ratatouille se congèle très bien en portions.",
    micros: ['Lycopène', 'Vitamine C', 'Fibres'],
    ing: [['Steak haché 5%', 130, 'Boucherie'], ['Courgette', 150, 'Légumes'], ['Aubergine', 120, 'Légumes'], ['Poivron', 100, 'Légumes'], ['Tomates concassées', 200, 'Conserves'], ['Huile d olive', 10, 'Épicerie'], ['Herbes de Provence', 3, 'Épicerie']],
    steps: "Légumes en cubes sautés 5 min, tomates concassées + herbes, mijote 20 min couvert. Steak grillé à part. Riche en fibres et très rassasiant pour peu de calories." },
  { id: 'r-wok-crevettes', name: 'Wok de crevettes aux légumes', meal: 'dîner', kcal: 420, p: 34, c: 40, f: 12, time: 15, cost: 4.0,
    micros: ['Iode', 'Sélénium', 'Zinc'],
    ing: [['Crevettes décortiquées', 150, 'Surgelés'], ['Nouilles de riz', 60, 'Épicerie'], ['Poivron', 100, 'Légumes'], ['Courgette', 100, 'Légumes'], ['Sauce soja', 15, 'Épicerie'], ['Gingembre frais', 5, 'Légumes']],
    steps: "Nouilles trempées 5 min dans l'eau chaude. Wok très chaud : crevettes 2 min, réserve. Légumes 3 min. Réunis avec nouilles + soja + gingembre." },
  { id: 'r-blanquette', name: 'Blanquette de dinde express', meal: 'dîner', kcal: 500, p: 40, c: 45, f: 13, time: 25, cost: 3.0, batch: true,
    batchNote: "Double les quantités : se réchauffe très bien.",
    micros: ['B3', 'B6', 'Sélénium'],
    ing: [['Escalope de dinde', 160, 'Boucherie'], ['Riz (cru)', 60, 'Épicerie'], ['Carottes', 120, 'Légumes'], ['Champignons', 100, 'Légumes'], ['Crème légère 15%', 60, 'Frais'], ['Bouillon de volaille', 200, 'Épicerie'], ['Citron', 15, 'Fruits']],
    steps: "Dinde en cubes + carottes rondelles dans le bouillon 15 min. Champignons 5 min. Crème + jus de citron en fin. Sers sur riz. Version légère du classique." },
  { id: 'r-shakshuka', name: 'Shakshuka sans œuf (tofu)', meal: 'dîner', kcal: 380, p: 22, c: 35, f: 16, time: 20, cost: 2.2,
    micros: ['Lycopène', 'Fer', 'Calcium'],
    ing: [['Tofu soyeux', 200, 'Frais'], ['Tomates concassées', 250, 'Conserves'], ['Poivron', 100, 'Légumes'], ['Cumin + paprika', 5, 'Épicerie'], ['Pain complet', 60, 'Boulangerie']],
    steps: "Poivron sauté 3 min. Tomates + épices, mijote 10 min. Découpe le tofu en cubes, niche-le dans la sauce 5 min. Sers avec pain pour tremper. Version végé sans œuf." },

  // ---------- COLLATIONS (compléments) ----------
  { id: 'r-energy-balls', name: 'Energy balls choco-avoine', meal: 'collation', kcal: 260, p: 10, c: 32, f: 12, time: 10, cost: 1.5, batch: true,
    batchNote: "Roule 12 boules d'un coup. 5 jours au frigo, 1 mois au congélateur.",
    micros: ['Magnésium', 'Fer', 'Fibres'],
    ing: [['Flocons d avoine', 60, 'Épicerie'], ['Beurre de cacahuète', 30, 'Épicerie'], ['Cacao non sucré', 10, 'Épicerie'], ['Miel', 15, 'Épicerie'], ['Whey chocolat', 15, 'Épicerie']],
    steps: "Mixe les flocons grossièrement. Mélange tout à la main. Roule en boules de 25 g. Frigo 1 h. Le snack portable et riche en énergie." },
  { id: 'r-banane-beurre', name: 'Banane + beurre de cacahuète', meal: 'collation', kcal: 240, p: 8, c: 30, f: 11, time: 2, cost: 0.8,
    micros: ['Potassium', 'Magnésium', 'B6'],
    ing: [['Banane', 120, 'Fruits'], ['Beurre de cacahuète', 20, 'Épicerie']],
    steps: "Coupe la banane en rondelles, tartine de beurre de cacahuète. Le snack pré-séance parfait : glucides rapides + lipides qui tiennent." },
  { id: 'r-cottage-tomate', name: 'Cottage cheese & tomates cerises', meal: 'collation', kcal: 200, p: 24, c: 10, f: 7, time: 3, cost: 1.6,
    micros: ['Calcium', 'Caséine', 'Lycopène'],
    ing: [['Cottage cheese', 200, 'Frais'], ['Tomates cerises', 100, 'Légumes'], ['Basilic', 3, 'Légumes'], ['Poivre', 1, 'Épicerie']],
    steps: "Cottage cheese dans un bol, tomates cerises coupées en deux, basilic, poivre. Collation ultra-protéinée à 200 kcal." },
  { id: 'r-smoothie-vert', name: 'Smoothie vert épinards-banane', meal: 'collation', kcal: 270, p: 22, c: 35, f: 5, time: 3, cost: 1.5,
    micros: ['Fer', 'Folates', 'Potassium'],
    ing: [['Épinards frais', 60, 'Légumes'], ['Banane', 100, 'Fruits'], ['Whey vanille', 25, 'Épicerie'], ['Lait demi-écrémé', 200, 'Frais']],
    steps: "Tout au blender 30 s. Les épinards sont indétectables au goût grâce à la banane. 60 g d'épinards = 2 portions de légumes." },

  // ---------- PETIT-DÉJ (nouveautés) ----------
  { id: 'r-porridge-vegan', name: 'Porridge vegan avoine-banane-chia', meal: 'petit-déj', kcal: 430, p: 16, c: 60, f: 14, time: 7, cost: 1.4,
    micros: ['Fibres', 'Oméga-3 ALA', 'Magnésium'], tags: ['Vegan', 'Fibres'],
    ing: [['Flocons d\'avoine', 60, 'Épicerie'], ['Lait d\'amande', 200, 'Frais'], ['Banane', 100, 'Fruits'], ['Beurre de cacahuète', 15, 'Épicerie'], ['Graines de chia', 10, 'Épicerie']],
    steps: "Flocons + lait d'amande 3 min à feu doux. Hors du feu, ajoute la banane écrasée, le beurre de cacahuète et les graines de chia. Laisse épaissir 2 min.",
    tip: "Le seul petit-déj 100 % végétal de l'app : combine avoine, cacahuète et chia pour un bon profil d'acides aminés sans produit animal." },
  { id: 'r-omelette-feta', name: 'Omelette épinards-féta', meal: 'petit-déj', kcal: 360, p: 28, c: 6, f: 25, time: 10, cost: 2.2,
    micros: ['Vitamine B12', 'Calcium', 'Choline'], tags: ['Riche en protéines', 'Low-carb', 'Express'],
    ing: [['Œufs', 120, 'Frais'], ['Blancs d\'œufs', 60, 'Frais'], ['Épinards frais', 60, 'Légumes'], ['Féta', 40, 'Frais'], ['Huile d\'olive', 5, 'Épicerie']],
    steps: "Bats les œufs et les blancs. Fais tomber les épinards 1 min à la poêle, verse les œufs, émiette la féta dessus. Plie quand le dessus est encore baveux.",
    tip: "Mélanger œufs entiers + blancs garde le repas riche en protéines tout en maîtrisant les lipides. La choline du jaune soutient mémoire et concentration." },
  { id: 'r-pancakes', name: 'Pancakes protéinés banane-avoine', meal: 'petit-déj', kcal: 420, p: 30, c: 52, f: 9, time: 12, cost: 1.7,
    micros: ['Potassium', 'Fibres', 'B2'], tags: ['Riche en protéines', 'Plaisir'],
    ing: [['Flocons d\'avoine', 50, 'Épicerie'], ['Œufs', 60, 'Frais'], ['Banane bien mûre', 100, 'Fruits'], ['Whey vanille', 25, 'Épicerie'], ['Lait demi-écrémé', 60, 'Frais'], ['Levure chimique', 3, 'Épicerie']],
    steps: "Mixe tout en pâte lisse. Petites louches sur poêle anti-adhésive feu moyen, retourne quand des bulles apparaissent. 2 min par face.",
    tip: "La banane bien mûre apporte le sucré : inutile d'ajouter du sucre. Idéal en petit-déj du week-end ou en collation post-séance." },
  { id: 'r-bircher', name: 'Bircher muesli pomme-cannelle', meal: 'petit-déj', kcal: 400, p: 24, c: 56, f: 10, time: 5, cost: 1.6, batch: true,
    batchNote: "Prépare 3 bols la veille : se conserve 3 jours au frigo.",
    micros: ['Fibres', 'Pectine', 'Calcium'], tags: ['Batch', 'Fibres'],
    ing: [['Flocons d\'avoine', 50, 'Épicerie'], ['Skyr nature', 150, 'Frais'], ['Lait demi-écrémé', 80, 'Frais'], ['Pomme', 120, 'Fruits'], ['Cannelle', 2, 'Épicerie'], ['Cerneaux de noix', 12, 'Épicerie']],
    steps: "Mélange flocons, skyr, lait et cannelle la veille. Le matin : râpe la pomme dessus, ajoute les noix. Frais et croquant.",
    tip: "La pectine de la pomme et les fibres de l'avoine forment un gel qui prolonge la satiété toute la matinée." },

  // ---------- DÉJEUNER (nouveautés) ----------
  { id: 'r-salade-beluga', name: 'Salade lentilles béluga, féta & betterave', meal: 'déjeuner', kcal: 470, p: 24, c: 52, f: 17, time: 15, cost: 2.4, batch: true,
    batchNote: "Se prépare en saladier pour 3 portions, 3 jours au frigo (ajoute la féta au moment de servir).",
    micros: ['Fer', 'Folates', 'Nitrates'], tags: ['Végétarien', 'Batch', 'Fibres'],
    ing: [['Lentilles béluga (crues)', 70, 'Épicerie'], ['Betterave cuite', 100, 'Légumes'], ['Féta', 40, 'Frais'], ['Roquette', 30, 'Légumes'], ['Huile d\'olive', 10, 'Épicerie'], ['Citron', 15, 'Fruits']],
    steps: "Lentilles béluga 18 min (elles tiennent et ne s'écrasent pas). Refroidies, mélange avec betterave en dés, roquette, féta émiettée. Vinaigrette huile-citron.",
    tip: "Les nitrates de la betterave améliorent l'oxygénation musculaire : un bon réflexe les jours d'entraînement intense." },
  { id: 'r-riz-cantonais', name: 'Riz cantonais protéiné (dinde & petits pois)', meal: 'déjeuner', kcal: 540, p: 38, c: 62, f: 13, time: 18, cost: 2.6, batch: true,
    batchNote: "Idéal pour recycler un reste de riz : double les quantités sans effort.",
    micros: ['B3', 'Fer', 'Sélénium'], tags: ['Riche en protéines', 'Anti-gaspi'],
    ing: [['Riz (cru)', 70, 'Épicerie'], ['Jambon de dinde', 80, 'Boucherie'], ['Œufs', 60, 'Frais'], ['Petits pois', 80, 'Surgelés'], ['Sauce soja', 12, 'Épicerie'], ['Ail', 4, 'Légumes']],
    steps: "Riz cuit refroidi. Brouille l'œuf à la poêle, réserve. Saute le jambon de dinde et les petits pois, ajoute le riz, l'œuf, la sauce soja. Bien chaud.",
    tip: "Le riz de la veille, refroidi, contient de l'amidon résistant : meilleure satiété et glycémie plus douce que le riz fraîchement cuit." },
  { id: 'r-couscous-poulet', name: 'Couscous semoule poulet-pois chiches', meal: 'déjeuner', kcal: 560, p: 42, c: 64, f: 12, time: 20, cost: 2.8, batch: true,
    batchNote: "Multiplie par 3 : la semoule se réchauffe en 1 min au micro-ondes.",
    micros: ['B6', 'Fibres', 'Sélénium'], tags: ['Riche en protéines', 'Batch'],
    ing: [['Semoule de couscous', 70, 'Épicerie'], ['Filet de poulet', 130, 'Boucherie'], ['Pois chiches (égouttés)', 80, 'Conserves'], ['Courgette', 120, 'Légumes'], ['Carotte', 80, 'Légumes'], ['Ras el-hanout', 4, 'Épicerie']],
    steps: "Semoule couverte d'eau bouillante salée 5 min, égraine à la fourchette. Poulet en dés saisi au ras el-hanout, ajoute légumes en dés et pois chiches, 8 min. Sers sur la semoule.",
    tip: "Poulet + pois chiches = combo qui pousse les protéines à 42 g tout en apportant fibres et satiété pour un déjeuner qui tient l'après-midi." },
  { id: 'r-bagel-saumon', name: 'Bagel complet saumon fumé & fromage frais', meal: 'déjeuner', kcal: 480, p: 32, c: 48, f: 17, time: 6, cost: 3.4,
    micros: ['Oméga-3 EPA/DHA', 'B12', 'Vitamine D'], tags: ['Express', 'Oméga-3'],
    ing: [['Pain complet', 90, 'Boulangerie'], ['Saumon fumé', 80, 'Frais'], ['Fromage frais', 40, 'Frais'], ['Concombre', 50, 'Légumes'], ['Aneth', 3, 'Légumes'], ['Citron', 10, 'Fruits']],
    steps: "Tartine le fromage frais, dépose le saumon fumé, le concombre en fines lamelles, l'aneth et un trait de citron. Déjeuner froid prêt en 6 min.",
    tip: "Le saumon fumé est l'une des rares sources alimentaires de vitamine D : précieux l'hiver pour l'immunité et les os." },

  // ---------- DÎNER (nouveautés) ----------
  { id: 'r-cabillaud-polenta', name: 'Cabillaud, polenta crémeuse & épinards', meal: 'dîner', kcal: 470, p: 40, c: 42, f: 13, time: 22, cost: 3.6,
    micros: ['Iode', 'Phosphore', 'B12'], tags: ['Riche en protéines', 'Sans gluten'],
    ing: [['Dos de cabillaud', 160, 'Poissonnerie'], ['Polenta (crue)', 60, 'Épicerie'], ['Épinards frais', 120, 'Légumes'], ['Lait demi-écrémé', 100, 'Frais'], ['Parmesan', 15, 'Frais'], ['Citron', 15, 'Fruits']],
    steps: "Polenta dans 250 ml d'eau + lait 8 min en remuant, parmesan en fin. Cabillaud poêlé 4 min par face. Épinards tombés à côté. Citron sur le poisson.",
    tip: "Le cabillaud est un poisson maigre ultra-protéiné (18 g/100 g) : parfait quand on veut beaucoup de protéines pour peu de calories et de lipides." },
  { id: 'r-maquereau-quinoa', name: 'Maquereau grillé, quinoa & poivrons', meal: 'dîner', kcal: 560, p: 36, c: 44, f: 26, time: 20, cost: 2.8,
    micros: ['Oméga-3 EPA/DHA', 'Vitamine D', 'Sélénium'], tags: ['Oméga-3', 'Économique'],
    ing: [['Filets de maquereau', 150, 'Poissonnerie'], ['Quinoa (cru)', 65, 'Épicerie'], ['Poivron', 150, 'Légumes'], ['Huile d\'olive', 8, 'Épicerie'], ['Citron', 20, 'Fruits'], ['Persil', 5, 'Légumes']],
    steps: "Quinoa 12 min. Poivrons en lanières rôtis 12 min au four. Maquereau côté peau 3 min puis 1 min. Citron et persil dessus.",
    tip: "Le maquereau est le champion oméga-3 le moins cher : 1 portion couvre largement la cible hebdomadaire de poisson gras." },
  { id: 'r-chili-sincarne', name: 'Chili sin carne haricots noirs (vegan)', meal: 'dîner', kcal: 490, p: 22, c: 78, f: 9, time: 25, cost: 1.6, batch: true,
    batchNote: "Congèle en portions : un dîner vegan complet toujours sous la main.",
    micros: ['Fer', 'Fibres', 'Magnésium'], tags: ['Vegan', 'Batch', 'Économique'],
    ing: [['Haricots noirs (égouttés)', 150, 'Conserves'], ['Tomates concassées', 200, 'Conserves'], ['Riz complet (cru)', 60, 'Épicerie'], ['Poivron', 100, 'Légumes'], ['Maïs', 60, 'Conserves'], ['Cumin + paprika fumé', 5, 'Épicerie']],
    steps: "Poivron sauté 3 min, ajoute tomates, haricots noirs, maïs et épices, mijote 15 min. Sers sur riz complet.",
    tip: "Légumineuse + céréale (haricots + riz) forme une protéine complète : indispensable pour couvrir tous les acides aminés sans viande." },
  { id: 'r-boulettes-dinde', name: 'Boulettes de dinde, courgette spaghetti & tomate', meal: 'dîner', kcal: 470, p: 44, c: 28, f: 20, time: 25, cost: 3.0, batch: true,
    batchNote: "Les boulettes se congèlent crues ou cuites : pratique en semaine.",
    micros: ['B3', 'Lycopène', 'Zinc'], tags: ['Riche en protéines', 'Low-carb'],
    ing: [['Dinde hachée', 160, 'Boucherie'], ['Courgette', 250, 'Légumes'], ['Coulis de tomate', 150, 'Conserves'], ['Chapelure', 15, 'Épicerie'], ['Ail', 5, 'Légumes'], ['Origan', 2, 'Épicerie']],
    steps: "Mélange dinde + chapelure + ail, forme des boulettes, dore-les 8 min. Ajoute le coulis, mijote 8 min. Courgette en spaghetti (économe) sautée 3 min à côté.",
    tip: "La courgette en spaghetti remplace les pâtes : on garde le plaisir d'un plat sauce tomate pour 3 fois moins de glucides." },
  { id: 'r-curry-poischiches', name: 'Curry de pois chiches épinards-coco (vegan)', meal: 'dîner', kcal: 520, p: 20, c: 72, f: 16, time: 20, cost: 1.8, batch: true,
    batchNote: "Encore meilleur réchauffé : double les quantités.",
    micros: ['Fer', 'Fibres', 'Curcumine'], tags: ['Vegan', 'Batch', 'Fibres'],
    ing: [['Pois chiches (égouttés)', 150, 'Conserves'], ['Lait de coco léger', 120, 'Conserves'], ['Épinards frais', 100, 'Légumes'], ['Tomates concassées', 150, 'Conserves'], ['Riz basmati (cru)', 60, 'Épicerie'], ['Curry + curcuma', 6, 'Épicerie']],
    steps: "Tomates + épices 5 min, ajoute pois chiches et lait de coco, mijote 10 min. Épinards en fin. Sers sur riz.",
    tip: "Le curcuma + une pincée de poivre noir décuple l'absorption de la curcumine, l'actif anti-inflammatoire de l'épice." },
  { id: 'r-steak-haricots-verts', name: 'Pavé de bœuf, haricots verts & pommes grenaille', meal: 'dîner', kcal: 540, p: 46, c: 38, f: 22, time: 25, cost: 4.0,
    micros: ['Fer héminique', 'Zinc', 'Vitamine C'], tags: ['Riche en protéines', 'Fer'],
    ing: [['Pavé de bœuf maigre', 160, 'Boucherie'], ['Pommes de terre grenaille', 200, 'Légumes'], ['Haricots verts', 150, 'Légumes'], ['Huile d\'olive', 8, 'Épicerie'], ['Ail', 5, 'Légumes'], ['Thym', 2, 'Épicerie']],
    steps: "Grenailles rôties 22 min au four avec ail et thym. Haricots verts vapeur 8 min. Pavé saisi 2-3 min par face, laisse reposer 3 min avant de trancher.",
    tip: "Laisser reposer la viande après cuisson redistribue les jus : elle reste tendre et juteuse plutôt que sèche." },

  // ---------- COLLATIONS (nouveautés) ----------
  { id: 'r-skyr-cacao', name: 'Skyr cacao-framboises', meal: 'collation', kcal: 230, p: 26, c: 22, f: 3, time: 2, cost: 1.4,
    micros: ['Calcium', 'Caséine lente', 'Antioxydants'], tags: ['Riche en protéines', 'Express', 'Low-fat'],
    ing: [['Skyr nature', 250, 'Frais'], ['Cacao non sucré', 6, 'Épicerie'], ['Framboises surgelées', 80, 'Surgelés'], ['Miel', 8, 'Épicerie']],
    steps: "Mélange skyr + cacao + miel. Framboises décongelées écrasées dessus. 26 g de protéines pour 230 kcal : la collation reine.",
    tip: "La caséine du skyr se digère lentement (6-7 h) : idéale le soir pour nourrir le muscle pendant le sommeil." },
  { id: 'r-edamame', name: 'Edamame vapeur au sel', meal: 'collation', kcal: 190, p: 17, c: 14, f: 8, time: 6, cost: 1.5,
    micros: ['Fer', 'Folates', 'Isoflavones'], tags: ['Végétarien', 'Riche en protéines', 'Express'],
    ing: [['Edamame (cosses)', 150, 'Surgelés'], ['Sel', 2, 'Épicerie'], ['Graines de sésame', 3, 'Épicerie']],
    steps: "Edamame 5 min à la vapeur (ou eau bouillante), sale et parsème de sésame. Presse les cosses pour sortir les graines.",
    tip: "Rare snack végétal aussi riche en protéines complètes : 17 g pour moins de 200 kcal, parfait devant un film sans culpabilité." },
  { id: 'r-mugcake', name: 'Mug cake protéiné chocolat (micro-ondes)', meal: 'collation', kcal: 280, p: 24, c: 28, f: 8, time: 4, cost: 1.3,
    micros: ['Magnésium', 'B12'], tags: ['Plaisir', 'Riche en protéines', 'Express'],
    ing: [['Whey chocolat', 30, 'Épicerie'], ['Flocons d\'avoine (mixés)', 25, 'Épicerie'], ['Œufs', 50, 'Frais'], ['Cacao non sucré', 5, 'Épicerie'], ['Lait demi-écrémé', 40, 'Frais'], ['Levure chimique', 2, 'Épicerie']],
    steps: "Mélange tout dans un mug. Micro-ondes 60-75 s (surveille : il doit rester moelleux). Le dessert qui rentre dans les macros.",
    tip: "Sors-le dès que le dessus est pris : 10 s de trop le rendent caoutchouteux. Le cœur continue de cuire hors du micro-ondes." }
];

// --- Badges --------------------------------------------------------------------
// check(s) reçoit les stats agrégées calculées par l'app.
window.BADGES = [
  { id: 'first-blood',  icon: '🩸', name: 'Première pierre',   desc: '1ʳᵉ séance enregistrée',            check: s => s.workouts >= 1 },
  { id: 'w5',           icon: '🔨', name: 'La machine démarre', desc: '5 séances',                         check: s => s.workouts >= 5 },
  { id: 'w15',          icon: '⚙️', name: 'Régulier',           desc: '15 séances',                        check: s => s.workouts >= 15 },
  { id: 'w30',          icon: '🏭', name: 'Infatigable',        desc: '30 séances',                        check: s => s.workouts >= 30 },
  { id: 'streak3',      icon: '✏️', name: 'Carnet ouvert',      desc: '3 jours de carnet d\'affilée',      check: s => s.journalStreak >= 3 },
  { id: 'streak7',      icon: '🔥', name: 'Semaine parfaite',   desc: '7 jours de carnet d\'affilée',      check: s => s.journalStreak >= 7 },
  { id: 'streak21',     icon: '🌋', name: 'Discipline de fer',  desc: '21 jours de carnet d\'affilée',     check: s => s.journalStreak >= 21 },
  { id: 'pr1',          icon: '🏆', name: 'Premier record',     desc: '1ᵉʳ record personnel battu',        check: s => s.prCount >= 1 },
  { id: 'pr10',         icon: '👑', name: 'Collectionneur',     desc: '10 records personnels',             check: s => s.prCount >= 10 },
  { id: 'vol10',        icon: '🐘', name: '10 tonnes',          desc: '10 000 kg de volume cumulé',        check: s => s.totalVolume >= 10000 },
  { id: 'vol50',        icon: '🚛', name: '50 tonnes',          desc: '50 000 kg de volume cumulé',        check: s => s.totalVolume >= 50000 },
  { id: 'sets100',      icon: '💯', name: 'Centurion',          desc: '100 séries validées',               check: s => s.totalSets >= 100 },
  { id: 'sets500',      icon: '🗿', name: 'Monument',           desc: '500 séries validées',               check: s => s.totalSets >= 500 },
  { id: 'weight7',      icon: '⚖️', name: 'Rigueur balance',    desc: '7 pesées sur une semaine',          check: s => s.weighWeek >= 7 },
  { id: 'pullup10',     icon: '🦍', name: 'Gorille',            desc: '10 tractions dans une série',       check: s => s.bestPullups >= 10 },
  { id: 'month1',       icon: '🌱', name: 'Un mois',            desc: '30 jours de carnet au total',       check: s => s.journalDays >= 30 },
  { id: 'w50',          icon: '🏛️', name: 'Titan',             desc: '50 séances',                        check: s => s.workouts >= 50 },
  { id: 'w100',         icon: '⚡', name: 'Légende',           desc: '100 séances',                       check: s => s.workouts >= 100 },
  { id: 'streak30',     icon: '💎', name: 'Habitude d\'acier',  desc: '30 jours de carnet d\'affilée',     check: s => s.journalStreak >= 30 },
  { id: 'streak60',     icon: '🌟', name: 'Incassable',        desc: '60 jours de carnet d\'affilée',     check: s => s.journalStreak >= 60 },
  { id: 'pr25',         icon: '🥇', name: 'Chasseur de records', desc: '25 records personnels',            check: s => s.prCount >= 25 },
  { id: 'pr50',         icon: '🏅', name: 'Briseur de limites', desc: '50 records personnels',             check: s => s.prCount >= 50 },
  { id: 'vol100',       icon: '🏔️', name: '100 tonnes',         desc: '100 000 kg de volume cumulé',       check: s => s.totalVolume >= 100000 },
  { id: 'sets1000',     icon: '🏰', name: 'Forteresse',        desc: '1 000 séries validées',             check: s => s.totalSets >= 1000 }
];

// --- Tips du jour ----------------------------------------------------------------
window.TIPS = [
  "Protéines : vise 1,6–2 g/kg/jour réparties sur 3–4 prises de ≥25 g pour maximiser la synthèse protéique.",
  "La progression se joue sur le carnet : bats tes chiffres de la semaine dernière d'1 rép ou 1 kg, pas plus.",
  "Sommeil < 6 h = -10 à -30 % de force le lendemain. La sieste de 20 min compense partiellement.",
  "RPE 8 = il te reste 2 répétitions en réserve. Si tu ne sais pas, c'est probablement un RPE 6.",
  "Hydratation : ~35 ml/kg/jour. Une perte de 2 % d'eau corporelle dégrade déjà la performance.",
  "Le déficit calorique se mesure sur la moyenne hebdo du poids, jamais sur un seul matin.",
  "Échauffement RAMP : élever la température, activer les muscles cibles, mobiliser les articulations, potentialiser avec 1–2 séries légères.",
  "Tempo 3010 : 3 s de descente contrôlée = plus de tension mécanique = plus d'hypertrophie à charge égale.",
  "Les courbatures ne mesurent pas l'efficacité d'une séance. La surcharge progressive, si.",
  "Pèse-toi le matin, à jeun, après être passé aux toilettes, dans les mêmes conditions chaque jour.",
  "Marche 7 000–10 000 pas/jour : le NEAT représente souvent plus de dépense que la séance elle-même.",
  "Une douleur articulaire qui dépasse 3/10 pendant un exercice = on régresse ou on remplace, jamais on serre les dents.",
  "Caféine 3–6 mg/kg, 45–60 min avant la séance : ergogène prouvé. Évite après 14 h si sommeil fragile.",
  "Plateau de poids depuis 2 semaines ? Ajoute d'abord 2 000 pas/jour avant de couper 100 kcal.",
  "Les glucides autour de l'entraînement (avant/après) soutiennent la performance et la récupération.",
  "Filme une série de temps en temps : la vidéo corrige la technique mieux que n'importe quel ressenti.",
  "La créatine monohydrate (3–5 g/jour, tous les jours) est le supplément le plus étudié et le plus efficace.",
  "Deload : toutes les 4–6 semaines, réduis le volume de 40–50 % pendant 1 semaine. Tu reviens plus fort.",
  "Mange tes protéines en premier dans l'assiette : satiété accrue, glycémie plus stable.",
  "Le muscle se construit pendant la récupération. La séance n'est que le stimulus.",
  "2 séances/semaine bien exécutées battent 5 séances bâclées. La constance gagne toujours.",
  "Étirements statiques longs AVANT la force = baisse de performance. Garde-les pour après ou le soir.",
  "Ton poids fluctue de ±1 kg avec l'eau, le sel et les glucides. Juge la tendance sur 7 jours.",
  "Respiration : inspire en descente, expire à l'effort. Gainage réflexe et tension maîtrisée.",
  "Prépare tes repas en lot 2×/semaine : la meilleure stratégie anti-craquage connue.",
  "Fibres : 25–35 g/jour (légumes, légumineuses, avoine) pour la satiété et la santé digestive.",
  "Si la motivation baisse : réduis l'objectif de la séance à 50 %. Une fois commencé, tu finiras souvent à 100 %.",
  "Oméga-3 (sardines, maquereau 2×/semaine) : anti-inflammatoire et soutien de la récupération.",
  "Le matériel ne fait pas le résultat : tension, effort proche de l'échec et progression suffisent.",
  "Note ton RPE à chaque série : c'est la donnée qui permet au coach d'ajuster ton volume.",
  "Le stress chronique élève le cortisol et favorise le stockage abdominal. 5 min de respiration lente le soir : 4 s inspire, 6 s expire.",
  "La surcharge progressive ne veut pas dire +5 kg à chaque séance. +1 rép, +1 s de tempo, -10 s de repos : tout ça compte.",
  "Les fibres dans l'assiette ralentissent la vidange gastrique : tu as moins faim et tes glucides sont mieux gérés par l'insuline.",
  "Unilatéral = double la difficulté sans changer la charge. Passe au curl unilatéral, au step-up unilatéral, au SDT unilatéral.",
  "Photos de progression : même éclairage, même heure, même lieu. La comparaison objective bat le miroir quotidien.",
  "La marche post-repas (15 min) réduit le pic glycémique de 30 %. Prends l'habitude après le déjeuner.",
  "Ne sous-estime pas les légumineuses : 25 g de protéines, 15 g de fibres et quasi zéro gras pour 100 g de lentilles sèches.",
  "Le magnésium améliore le sommeil et réduit les crampes. Sources : amandes, chocolat noir, eaux minérales riches (Hépar, Contrex).",
  "Mange une protéine complète à chaque repas (animale, ou légumineuse + céréale) : c'est le profil d'acides aminés qui pilote la construction musculaire.",
  "Excentrique lent (3-4 s à la descente) = plus de micro-dommages utiles et plus de gains de force qu'une descente subie.",
  "L'amplitude complète bat la charge lourde tronquée : un mouvement complet à charge modérée recrute plus de fibres et protège mieux les articulations.",
  "Garde toujours 1 à 3 répétitions en réserve (RIR) sur tes séries de travail : tu progresses sans cramer ta récupération.",
  "Le poisson gras 2×/semaine (maquereau, sardines, saumon) couvre tes oméga-3 EPA/DHA, anti-inflammatoires et alliés de la récupération.",
  "La vitamine C des légumes crus (poivron, brocoli, agrumes) multiplie l'absorption du fer végétal des lentilles et épinards.",
  "Un échauffement de 5 min de mobilité ciblée (hanches, épaules, chevilles) débloque plus d'amplitude qu'il n'en fait perdre en fatigue.",
  "La constance bat l'intensité : 3 séances correctes chaque semaine pendant 3 mois transforment un physique. Une séance héroïque, non.",
  "Tes glucides ne te font pas grossir : c'est le surplus calorique total. Place-les surtout autour de l'entraînement pour la performance.",
  "Varie tes sources de protéines (œufs, poisson, volaille, légumineuses, laitages) : tu couvres mieux micronutriments et acides aminés.",
  "Le sommeil est ton premier anabolisant : 7-9 h régulières font plus pour tes muscles que n'importe quel complément.",
  "Bois un grand verre d'eau au réveil : on se réveille déshydraté, et la vigilance comme la performance en dépendent."
];

// --- Catalogue matériel (pour l'onboarding et les réglages) --------------------
window.EQUIPMENT_OPTIONS = [
  { id: 'halteres',       label: 'Haltères',              icon: '🏋️' },
  { id: 'barre',          label: 'Barre de traction',      icon: '🔱' },
  { id: 'chaise_romaine', label: 'Chaise romaine',         icon: '🪑' },
  { id: 'banc',           label: 'Banc plat/incliné',      icon: '📐' },
  { id: 'elastiques',     label: 'Élastiques/bandes',      icon: '🟩' },
  { id: 'kettlebell',     label: 'Kettlebell',              icon: '🔔' },
  { id: 'anneaux',        label: 'Anneaux de gym',         icon: '⭕' },
  { id: 'barre_sol',      label: 'Barre + disques',        icon: '🏗️' },
  { id: 'ab_wheel',       label: 'Roue abdominale',        icon: '☸️' },
  { id: 'corde',          label: 'Corde à sauter',         icon: '🪢' },
  { id: 'step',           label: 'Marche / step',          icon: '🪜' },
  { id: 'poids_corps',    label: 'Poids du corps seul',    icon: '🤸' }
];

// --- Catalogue exclusions alimentaires -----------------------------------------
window.EXCLUSION_OPTIONS = [
  { id: 'oeufs',          label: 'Œufs',                   icon: '🥚' },
  { id: 'oignons',        label: 'Oignons / ail',          icon: '🧅' },
  { id: 'lactose',        label: 'Lactose (lait, fromage)', icon: '🥛' },
  { id: 'gluten',         label: 'Gluten (blé, orge…)',    icon: '🌾' },
  { id: 'fruits_de_mer',  label: 'Poisson / fruits de mer',icon: '🐟' },
  { id: 'viande_rouge',   label: 'Viande rouge',           icon: '🥩' },
  { id: 'volaille',       label: 'Volaille',               icon: '🍗' },
  { id: 'legumineuses',   label: 'Légumineuses (pois, lentilles)', icon: '🫘' },
  { id: 'noix',           label: 'Fruits à coque',         icon: '🥜' },
  { id: 'soja',           label: 'Soja',                   icon: '🫛' },
  { id: 'sucre',          label: 'Sucre ajouté',           icon: '🍬' },
  { id: 'alcool',         label: 'Alcool (dans recettes)', icon: '🍾' },
  { id: 'cafe',           label: 'Caféine / café',         icon: '☕' },
  { id: 'porc',           label: 'Porc / charcuterie',     icon: '🐷' },
  { id: 'vegan',          label: 'Vegan (aucun produit animal)', icon: '🌱' }
];

// --- Catalogue thèmes visuels --------------------------------------------------
window.ACCENT_PRESETS = [
  { id: 'blue',    label: 'BLEU',      value: '#2F80ED' },
  { id: 'teal',    label: 'TURQUOISE', value: '#0FB5AE' },
  { id: 'green',   label: 'VERT',      value: '#16A34A' },
  { id: 'indigo',  label: 'INDIGO',    value: '#6366F1' },
  { id: 'purple',  label: 'VIOLET',    value: '#9333EA' },
  { id: 'coral',   label: 'CORAIL',    value: '#F2674E' },
  { id: 'rose',    label: 'ROSE',      value: '#EC4899' },
  { id: 'amber',   label: 'AMBRE',     value: '#D98A00' },
  { id: 'slate',   label: 'ARDOISE',   value: '#64748B' },
  { id: 'custom',  label: 'LIBRE',     value: null }
];

window.FONT_PRESETS = [
  { id: 'inter',   label: 'Inter',    family: '"Inter", system-ui, sans-serif',    url: 'Inter:wght@400;450;500;600;700;800' },
  { id: 'outfit',  label: 'Outfit',   family: '"Outfit", system-ui, sans-serif',   url: 'Outfit:wght@400;500;600;700;800' },
  { id: 'poppins', label: 'Poppins',  family: '"Poppins", system-ui, sans-serif',  url: 'Poppins:wght@400;500;600;700;800' },
  { id: 'nunito',  label: 'Nunito',   family: '"Nunito", system-ui, sans-serif',   url: 'Nunito:wght@400;500;600;700;800' },
  { id: 'roboto',  label: 'Roboto',   family: '"Roboto", system-ui, sans-serif',   url: 'Roboto:wght@400;500;700;900' },
  { id: 'system',  label: 'Système',  family: 'system-ui, -apple-system, "Segoe UI", sans-serif', url: null }
];
