// ============================================================
// RECOMP — Bibliothèque d'exercices
// Champs : id, name, group (groupe musculaire), muscles [principaux],
// secondary [secondaires], level (1-3), equip, steps [exécution],
// cues (consignes clés), errors [erreurs fréquentes], breath (respiration),
// easier / harder (régression / progression), flag ('clavicule' si poussée à risque)
// ============================================================

window.EXLIB = [
  // ================= JAMBES =================
  { id: 'goblet-squat', name: 'Goblet squat', group: 'Jambes', muscles: ['Quadriceps', 'Fessiers'], secondary: ['Gainage'], level: 1, equip: 'Haltère',
    steps: ["Haltère vertical tenu contre le sternum, coudes sous la charge.", "Pieds largeur épaules, pointes légèrement ouvertes.", "Descends en 3 s, hanches entre les talons, buste droit.", "Remonte en poussant le sol, talons ancrés."],
    cues: "Les coudes passent entre les genoux en bas. Le poids devant agit comme contrepoids : profite-en pour descendre profond.",
    errors: ["Talons qui décollent", "Genoux qui rentrent vers l'intérieur", "Dos qui s'arrondit en bas"],
    breath: "Inspire en haut, bloque pendant la descente, expire à la remontée.",
    easier: 'box-squat', harder: 'bulgarian-split' },
  { id: 'bulgarian-split', name: 'Squat bulgare', group: 'Jambes', muscles: ['Quadriceps', 'Fessiers'], secondary: ['Équilibre'], level: 3, equip: 'Haltère + chaise/banc',
    steps: ["Pied arrière posé sur une chaise, lacets vers le bas.", "Pied avant à ~60 cm de la chaise.", "Descends verticalement jusqu'à ce que le genou arrière frôle le sol.", "Pousse dans le talon avant pour remonter."],
    cues: "90 % du poids sur la jambe avant. Buste légèrement penché = plus de fessier ; buste droit = plus de quadriceps.",
    errors: ["Pied avant trop près (genou qui dépasse trop)", "Rebond en bas", "Bassin qui tourne"],
    breath: "Inspire en descente, expire en poussée.",
    easier: 'rear-lunge', harder: 'pistol-squat' },
  { id: 'rear-lunge', name: 'Fentes arrière', group: 'Jambes', muscles: ['Quadriceps', 'Fessiers'], secondary: ['Ischio-jambiers'], level: 1, equip: 'Haltères (option)',
    steps: ["Debout, haltères le long du corps.", "Grand pas en arrière, pose la pointe du pied.", "Descends jusqu'à ce que le genou arrière frôle le sol, tibia avant vertical.", "Pousse dans le talon avant pour revenir."],
    cues: "Le pas arrière protège le genou avant (moins de cisaillement que la fente avant). Bassin neutre, regard loin devant.",
    errors: ["Pas trop court", "Buste qui s'effondre en avant", "Poussée sur la jambe arrière"],
    breath: "Inspire en descente, expire au retour.",
    easier: 'lateral-lunge', harder: 'walking-lunge' },
  { id: 'walking-lunge', name: 'Fentes marchées', group: 'Jambes', muscles: ['Quadriceps', 'Fessiers'], secondary: ['Gainage'], level: 2, equip: 'Haltères',
    steps: ["Enchaîne les fentes en avançant, sans pause entre les pas.", "Chaque genou arrière frôle le sol.", "Garde le buste fier et les haltères stables."],
    cues: "Plus métabolique que la fente statique : idéal en fin de séance pour finir les jambes.",
    errors: ["Pas trop rapides et écourtés", "Déséquilibre latéral"],
    breath: "Rythme respiratoire continu, expire à chaque poussée.",
    easier: 'rear-lunge', harder: 'bulgarian-split' },
  { id: 'romanian-dl', name: 'Soulevé de terre roumain', group: 'Jambes', muscles: ['Ischio-jambiers', 'Fessiers'], secondary: ['Lombaires', 'Avant-bras'], level: 2, equip: 'Haltères',
    steps: ["Haltères devant les cuisses, pieds largeur bassin.", "Pousse les hanches en arrière, genoux légèrement fléchis (angle fixe).", "Descends les haltères au contact des jambes jusqu'à l'étirement net des ischios.", "Remonte en contractant les fessiers, hanches vers l'avant."],
    cues: "C'est une charnière de hanche, pas un squat : les genoux ne plient presque pas. Dos neutre du début à la fin.",
    errors: ["Dos arrondi", "Haltères qui s'éloignent des jambes", "Descendre trop bas en perdant la position"],
    breath: "Inspire en haut, descends gainé, expire à la remontée.",
    easier: 'glute-bridge', harder: 'single-rdl' },
  { id: 'single-rdl', name: 'SDT roumain unilatéral', group: 'Jambes', muscles: ['Ischio-jambiers', 'Fessiers'], secondary: ['Équilibre', 'Gainage'], level: 3, equip: 'Haltère',
    steps: ["Haltère dans la main opposée à la jambe d'appui.", "Bascule le buste en avant en tendant la jambe libre derrière.", "Descends jusqu'à l'étirement, hanches restées carrées.", "Remonte en serrant le fessier d'appui."],
    cues: "Imagine tes hanches comme des phares de voiture : ils doivent rester face au sol, sans rotation.",
    errors: ["Rotation du bassin", "Genou d'appui verrouillé", "Aller trop vite"],
    breath: "Lent et contrôlé, expire en remontant.",
    easier: 'romanian-dl', harder: null },
  { id: 'hip-thrust', name: 'Hip thrust (haltère)', group: 'Jambes', muscles: ['Fessiers'], secondary: ['Ischio-jambiers'], level: 1, equip: 'Haltère + chaise/banc',
    steps: ["Haut du dos appuyé sur le bord d'une chaise stable, haltère sur le bassin.", "Pieds à plat, tibias verticaux en position haute.", "Monte le bassin jusqu'à l'alignement épaules-genoux.", "Pause 1 s en haut en serrant fort, redescends contrôlé."],
    cues: "Menton rentré, regard vers l'avant (pas le plafond) pour éviter l'hyperextension lombaire.",
    errors: ["Pousser avec les lombaires au lieu des fessiers", "Pieds trop loin (ischio) ou trop près (quadri)"],
    breath: "Expire en montée, inspire en descente.",
    easier: 'glute-bridge', harder: null },

  { id: 'calf-raise', name: 'Mollets debout', group: 'Jambes', muscles: ['Mollets'], secondary: ['Équilibre'], level: 1, equip: 'Haltères + marche (option)',
    steps: ["Debout, haltères en main, idéalement l'avant-pied sur une marche.", "Descends le talon sous le niveau de la marche : étirement 1 s.", "Monte le plus haut possible sur la pointe : contraction 1 s."],
    cues: "L'amplitude complète fait toute la différence : la plupart des gens ne travaillent que la moitié du mouvement.",
    errors: ["Rebondir", "Amplitude écourtée", "Genoux qui plient"],
    breath: "Respiration libre et régulière.",
    easier: null, harder: 'calf-single' },
  { id: 'calf-single', name: 'Mollets unilatéral', group: 'Jambes', muscles: ['Mollets'], secondary: ['Équilibre'], level: 2, equip: 'Haltère + marche',
    steps: ["Un seul pied sur la marche, haltère du même côté.", "Même amplitude complète, l'autre main tient un appui pour l'équilibre."],
    cues: "Double l'intensité sans plus de charge : parfait quand 16 kg deviennent légers à deux jambes.",
    errors: ["S'aider en tirant sur l'appui", "Écourter le bas du mouvement"],
    breath: "Respiration libre.",
    easier: 'calf-raise', harder: null },
  { id: 'sumo-squat', name: 'Squat sumo haltère', group: 'Jambes', muscles: ['Adducteurs', 'Fessiers'], secondary: ['Quadriceps'], level: 1, equip: 'Haltère',
    steps: ["Pieds très écartés, pointes à 45°.", "Haltère tenu à deux mains entre les jambes.", "Descends genoux dans l'axe des pointes, buste vertical."],
    cues: "Cible l'intérieur des cuisses, zone souvent oubliée. Pousse les genoux vers l'extérieur tout le long.",
    errors: ["Genoux qui rentrent", "Buste qui penche"],
    breath: "Inspire en bas, expire en poussant.",
    easier: null, harder: 'goblet-squat' },
  { id: 'box-squat', name: 'Box squat (chaise)', group: 'Jambes', muscles: ['Quadriceps', 'Fessiers'], secondary: ['Ischio-jambiers'], level: 1, equip: 'Chaise',
    steps: ["Squat jusqu'à effleurer la chaise (sans s'asseoir complètement).", "Pause 1 s en touchant, puis remonte sans élan."],
    cues: "Parfait pour apprendre la profondeur et la confiance. La chaise est un repère, pas un siège.",
    errors: ["S'écrouler sur la chaise", "Se pencher pour se relancer"],
    breath: "Expire en remontant.",
    easier: null, harder: 'goblet-squat' },

  // ================= DOS =================
  { id: 'pullup', name: 'Tractions pronation', group: 'Dos', muscles: ['Grand dorsal', 'Biceps'], secondary: ['Avant-bras', 'Gainage'], level: 3, equip: 'Barre de traction',
    steps: ["Prise pronation (paumes vers l'avant), un peu plus large que les épaules.", "Départ bras tendus, omoplates tirées vers le bas.", "Tire les coudes vers les hanches jusqu'au menton au-dessus de la barre.", "Descends en 2 s complet, sans lâcher la tension."],
    cues: "Pense « coudes vers les poches arrière », pas « menton vers la barre ». Le dos tire, les bras suivent.",
    errors: ["Demi-amplitude en bas", "Balancier (kipping)", "Épaules qui montent aux oreilles"],
    breath: "Expire en tirant, inspire en descendant.",
    easier: 'pullup-neg', harder: null },
  { id: 'pullup-neutral', name: 'Tractions prise neutre', group: 'Dos', muscles: ['Grand dorsal', 'Biceps'], secondary: ['Brachial'], level: 3, equip: 'Barre (poignées parallèles)',
    steps: ["Paumes face à face.", "Même exécution que la traction pronation."],
    cues: "Prise la plus confortable pour les épaules et les coudes — souvent la meilleure option avec un antécédent à la clavicule.",
    errors: ["Mêmes que la traction classique"],
    breath: "Expire en tirant.",
    easier: 'pullup-neg', harder: 'pullup' },
  { id: 'pullup-neg', name: 'Tractions négatives', group: 'Dos', muscles: ['Grand dorsal', 'Biceps'], secondary: ['Avant-bras'], level: 2, equip: 'Barre + chaise',
    steps: ["Monte à la barre en t'aidant d'une chaise.", "Position haute : menton au-dessus de la barre.", "Descends LE PLUS LENTEMENT possible (vise 5 s).", "Repose les pieds, remonte avec la chaise, répète."],
    cues: "La phase négative construit la force qui te donnera tes premières tractions complètes. 3×5 négatives lentes = programme d'accès aux tractions.",
    errors: ["Descendre trop vite", "Sauter la fin du mouvement"],
    breath: "Inspire en haut, souffle long pendant la descente.",
    easier: 'inverted-row', harder: 'pullup-neutral' },
  { id: 'inverted-row', name: 'Rowing inversé (table)', group: 'Dos', muscles: ['Grand dorsal', 'Trapèzes'], secondary: ['Biceps', 'Gainage'], level: 1, equip: 'Table solide',
    steps: ["Allongé sous une table robuste, attrape le bord, prise large.", "Corps gainé en planche, talons au sol.", "Tire la poitrine vers le bord de la table.", "Pause 1 s, redescends contrôlé."],
    cues: "Pieds plus loin = plus difficile ; genoux pliés = plus facile. Vérifie 2 fois la stabilité de la table.",
    errors: ["Bassin qui tombe", "Demi-amplitude", "Coup de rein pour monter"],
    breath: "Expire en tirant.",
    easier: null, harder: 'pullup-neg' },
  { id: 'db-row', name: 'Rowing unilatéral haltère', group: 'Dos', muscles: ['Grand dorsal', 'Trapèzes'], secondary: ['Biceps', 'Lombaires'], level: 1, equip: 'Haltère + appui',
    steps: ["Main et genou opposés sur une chaise/banc, dos plat parallèle au sol.", "Haltère bras tendu, épaule relâchée vers le sol.", "Tire le coude le long du corps vers la hanche.", "Serre l'omoplate 1 s en haut, redescends en étirement complet."],
    cues: "Le coude reste collé aux côtes : s'il s'écarte, ce sont les épaules qui prennent le relais.",
    errors: ["Rotation du buste pour monter plus haut", "Tirer avec le biceps seul", "Dos arrondi"],
    breath: "Expire en tirant.",
    easier: 'inverted-row', harder: null },
  { id: 'bent-row', name: 'Rowing penché 2 haltères', group: 'Dos', muscles: ['Grand dorsal', 'Trapèzes'], secondary: ['Lombaires', 'Biceps'], level: 2, equip: 'Haltères',
    steps: ["Buste penché à ~45°, dos neutre, genoux souples.", "Haltères bras tendus sous les épaules.", "Tire les deux coudes vers les hanches simultanément.", "Contrôle la descente."],
    cues: "Le gainage lombaire travaille autant que le dos : si la position te fatigue les lombaires avant le dos, repasse à l'unilatéral avec appui.",
    errors: ["Buste qui se redresse à chaque rep", "À-coups"],
    breath: "Expire en tirant, gaine en isométrie.",
    easier: 'db-row', harder: null },
  { id: 'shrugs', name: 'Shrugs haltères', group: 'Dos', muscles: ['Trapèzes supérieurs'], secondary: ['Avant-bras'], level: 1, equip: 'Haltères',
    steps: ["Debout, haltères le long du corps.", "Hausse les épaules verticalement le plus haut possible.", "Pause 1 s, redescends lentement en étirement."],
    cues: "Montée/descente PURE : aucune rotation des épaules (la rotation sous charge use l'articulation pour rien).",
    errors: ["Rouler les épaules", "Plier les coudes", "Amplitude minuscule"],
    breath: "Expire en haussant.",
    easier: null, harder: null },
  { id: 'superman', name: 'Superman au sol', group: 'Dos', muscles: ['Lombaires'], secondary: ['Fessiers', 'Trapèzes'], level: 1, equip: 'Poids du corps',
    steps: ["Allongé sur le ventre, bras devant.", "Décolle simultanément bras et jambes de quelques centimètres.", "Tiens 2 s, redescends sans poser complètement."],
    cues: "Regard au sol, nuque dans le prolongement du dos. Pense « m'allonger » plutôt que « monter haut ».",
    errors: ["Hyperextension du cou", "Monter trop haut en cambrant"],
    breath: "Expire en montant, respire en tenant.",
    easier: null, harder: 'back-ext' },
  { id: 'back-ext', name: 'Extensions lombaires (chaise romaine)', group: 'Dos', muscles: ['Lombaires'], secondary: ['Fessiers', 'Ischio-jambiers'], level: 2, equip: 'Chaise romaine',
    steps: ["Bassin calé sur le support, chevilles bloquées.", "Descends le buste contrôlé.", "Remonte jusqu'à l'ALIGNEMENT du corps — jamais au-delà.", "Pause 2 s en haut, gainage abdominal constant."],
    cues: "L'hyperextension (monter au-delà de l'horizontale) comprime les disques : l'alignement suffit largement pour renforcer.",
    errors: ["Hyperextension en haut", "Mouvement balistique", "Mains derrière la nuque qui tirent sur le cou"],
    breath: "Inspire en descente, expire en remontée.",
    easier: 'superman', harder: null },

  // ================= POUSSÉE (adaptée clavicule) =================
  { id: 'incline-pushup', name: 'Pompes surélevées', group: 'Poussée', muscles: ['Pectoraux', 'Triceps'], secondary: ['Épaules', 'Gainage'], level: 1, equip: 'Table/mur', flag: 'clavicule',
    steps: ["Mains sur un support stable (table, plan de travail), corps en planche.", "Descends la poitrine vers le support en 2 s, coudes à ~45° du corps.", "Pousse pour revenir, sans verrouiller brutalement."],
    cues: "Plus le support est haut, plus c'est facile : règle la difficulté au centimètre. La meilleure option de poussée avec un antécédent clavicule/épaule.",
    errors: ["Coudes qui partent à 90° du buste", "Bassin qui tombe", "Amplitude réduite"],
    breath: "Inspire en descente, expire en poussée.",
    easier: null, harder: 'pushup' },
  { id: 'pushup', name: 'Pompes au sol', group: 'Poussée', muscles: ['Pectoraux', 'Triceps'], secondary: ['Épaules', 'Gainage'], level: 2, equip: 'Poids du corps', flag: 'clavicule',
    steps: ["Mains légèrement plus larges que les épaules.", "Corps rigide de la tête aux talons.", "Poitrine à 2 cm du sol, coudes à 45°.", "Poussée complète sans casser la ligne du corps."],
    cues: "⚠️ Avec un antécédent clavicule : n'y passe que si les pompes surélevées sont parfaitement indolores depuis 2 semaines.",
    errors: ["Tête qui plonge en avant", "Demi-amplitude", "Coudes évasés"],
    breath: "Inspire en bas, expire en haut.",
    easier: 'incline-pushup', harder: 'dips-partial' },
  { id: 'dips-partial', name: 'Dips amplitude partielle', group: 'Poussée', muscles: ['Triceps', 'Pectoraux inférieurs'], secondary: ['Épaules'], level: 3, equip: 'Chaise romaine / barres', flag: 'clavicule',
    steps: ["Buste QUASI VERTICAL (protège l'épaule).", "Descends en 2 s jusqu'à coudes à 90° MAXIMUM.", "Remonte en poussant, sans verrouiller sèchement."],
    cues: "⚠️ PROTOCOLE CONDITIONNEL : au moindre inconfort articulaire (clavicule, épaule, sternum) → arrêt immédiat et remplacement par pompes surélevées. Aucune négociation.",
    errors: ["Descendre trop bas (zone dangereuse pour l'épaule)", "Buste penché en avant", "Épaules qui remontent"],
    breath: "Inspire en descente, expire en poussée.",
    easier: 'incline-pushup', harder: null },
  { id: 'knee-pushup', name: 'Pompes genoux', group: 'Poussée', muscles: ['Pectoraux', 'Triceps'], secondary: ['Gainage'], level: 1, equip: 'Poids du corps', flag: 'clavicule',
    steps: ["Même exécution que la pompe classique, appui sur les genoux.", "Garde la ligne épaules-bassin-genoux rigide."],
    cues: "Étape intermédiaire entre pompes surélevées et pompes complètes.",
    errors: ["Casser à la hanche", "Amplitude réduite"],
    breath: "Expire en poussant.",
    easier: 'incline-pushup', harder: 'pushup' },

  // ================= BRAS =================
  { id: 'db-curl', name: 'Curl haltères alterné', group: 'Bras', muscles: ['Biceps'], secondary: ['Avant-bras'], level: 1, equip: 'Haltères',
    steps: ["Debout, haltères en supination le long du corps.", "Monte un haltère en gardant le coude collé au buste.", "Supination complète en haut, serre 1 s.", "Descends en 2 s, alterne."],
    cues: "Le coude est une charnière fixe : s'il avance, l'épaule vole le travail du biceps.",
    errors: ["Élan du buste", "Coudes qui avancent", "Descente en chute libre"],
    breath: "Expire en montée.",
    easier: null, harder: 'conc-curl' },

  { id: 'conc-curl', name: 'Curl concentré', group: 'Bras', muscles: ['Biceps'], secondary: ['Brachial'], level: 2, equip: 'Haltère + chaise',
    steps: ["Assis, coude calé contre l'intérieur de la cuisse.", "Monte l'haltère en gardant le bras plaqué.", "Contraction maximale 1 s, descente très lente."],
    cues: "Zéro triche possible : c'est l'exercice de finition pour sentir le biceps travailler à 100 %.",
    errors: ["S'aider de l'épaule", "Aller trop lourd"],
    breath: "Expire en montée.",
    easier: 'db-curl', harder: null },
  { id: 'kickback', name: 'Kickback triceps', group: 'Bras', muscles: ['Triceps'], secondary: ['Arrière d\\'épaule'], level: 1, equip: 'Haltère + appui',
    steps: ["Buste penché, main en appui, coude levé collé au buste, bras parallèle au sol.", "Tends le coude vers l'arrière jusqu'au bras tendu.", "Serre 1 s, reviens contrôlé sans bouger le coude."],
    cues: "Mouvement de triceps sans aucune contrainte sur l'épaule/clavicule : idéal pour ton profil.",
    errors: ["Coude qui descend", "Élan du bras entier"],
    breath: "Expire en tendant.",
    easier: null, harder: null },

  // ================= ABDOS / GAINAGE =================
  { id: 'plank', name: 'Planche', group: 'Abdos', muscles: ['Transverse', 'Grand droit'], secondary: ['Épaules', 'Fessiers'], level: 1, equip: 'Poids du corps',
    steps: ["Appui sur les avant-bras, coudes sous les épaules.", "Corps aligné tête-bassin-talons.", "Bascule légèrement le bassin en rétroversion, serre fessiers et abdos.", "Respire normalement en tenant."],
    cues: "Une planche sans rétroversion du bassin n'est qu'une posture. Serre comme si tu allais recevoir un coup au ventre.",
    errors: ["Bassin qui tombe (cambrure)", "Fesses en l'air", "Apnée"],
    breath: "Respiration continue, jamais bloquée.",
    easier: null, harder: 'plank-side' },
  { id: 'plank-side', name: 'Planche latérale', group: 'Abdos', muscles: ['Obliques'], secondary: ['Moyen fessier'], level: 2, equip: 'Poids du corps',
    steps: ["Appui sur un avant-bras, coude sous l'épaule, pieds empilés.", "Monte le bassin pour aligner le corps.", "Tiens, puis change de côté."],
    cues: "Travaille la sangle latérale et stabilise le bassin — utile pour les fentes et le SDT unilatéral.",
    errors: ["Bassin qui plonge", "Épaule qui s'effondre"],
    breath: "Continue.",
    easier: 'plank', harder: null },

  { id: 'hollow', name: 'Hollow hold', group: 'Abdos', muscles: ['Grand droit', 'Transverse'], secondary: ['Fléchisseurs de hanche'], level: 3, equip: 'Poids du corps',
    steps: ["Allongé, décolle épaules et jambes, lombaires plaquées.", "Bras tendus derrière la tête, corps en banane creuse.", "Tiens la position sans casser."],
    cues: "Le gainage des gymnastes : transfère directement vers les tractions et le contrôle du corps.",
    errors: ["Lombaires qui décollent (raccourcis en pliant les genoux)"],
    breath: "Respiration courte mais continue.",
    easier: 'dead-bug', harder: 'ab-wheel' },
  { id: 'leg-raise', name: 'Relevés de jambes (chaise romaine)', group: 'Abdos', muscles: ['Grand droit', 'Fléchisseurs de hanche'], secondary: ['Avant-bras'], level: 2, equip: 'Chaise romaine',
    steps: ["Avant-bras sur les supports, dos contre le dossier.", "Monte les genoux vers la poitrine.", "FIN DE MOUVEMENT : enroule le bassin vers l'avant (rétroversion).", "Descends en 2 s sans balancer."],
    cues: "Sans l'enroulement final du bassin, ce sont surtout les fléchisseurs de hanche qui bossent, pas les abdos.",
    errors: ["Balancier", "Jambes qui tombent en chute libre", "Épaules remontées aux oreilles"],
    breath: "Expire en montant les genoux.",
    easier: 'dead-bug', harder: null },
  { id: 'weighted-crunch', name: 'Crunch lesté', group: 'Abdos', muscles: ['Grand droit'], secondary: ['Obliques'], level: 1, equip: 'Haltère',
    steps: ["Allongé, genoux pliés, haltère tenu sur la poitrine.", "Décolle les omoplates en enroulant la colonne.", "Pause 1 s en haut, descente lente."],
    cues: "Le bas du dos reste au sol : on enroule, on ne s'assoit pas. Amplitude courte mais sous tension.",
    errors: ["Tirer sur la nuque", "Monter trop haut (psoas)"],
    breath: "Expire en montant.",
    easier: null, harder: 'leg-raise' },
  { id: 'russian-twist', name: 'Russian twist (haltère)', group: 'Abdos', muscles: ['Obliques'], secondary: ['Grand droit'], level: 2, equip: 'Haltère',
    steps: ["Assis, buste incliné à 45°, haltère tenu à deux mains.", "Tourne le buste d'un côté à l'autre, contrôlé.", "Le mouvement vient du buste, pas des bras."],
    cues: "Garde le dos droit (pas arrondi). Pieds au sol = plus facile ; décollés = plus dur.",
    errors: ["Bouger seulement les bras", "Dos arrondi", "Vitesse incontrôlée"],
    breath: "Expire à chaque rotation.",
    easier: 'plank-side', harder: null }
,

  // ==============================
  // JAMBES — extensions
  // ==============================
  { id: 'wall-sit', name: 'Wall Sit (isométrique)', group: 'Jambes',
    muscles: ['Quadriceps', 'Fessiers'], secondary: ['Ischio-jambiers'],
    level: 1, equip: 'Poids du corps',
    steps: ['Dos plat contre le mur.', 'Descends jusqu\'à 90° de flexion de genou.', 'Tiens la position : respiration régulière, quadris contractés.'],
    cues: 'Pense à pousser ton dos dans le mur — ça stabilise les lombaires et maximise le recrutement quad.',
    errors: ['Talons décollés', 'Angle > 90° (trop facile)', 'Apnée'],
    breath: 'Respiration lente et contrôlée tout au long de la tenue.',
    easier: null, harder: 'bulgarian-split', flag: null },

  { id: 'step-up', name: 'Step-up haltère', group: 'Jambes',
    muscles: ['Quadriceps', 'Fessiers'], secondary: ['Ischio-jambiers', 'Mollets'],
    level: 2, equip: 'Haltères + marche/banc',
    steps: ['Haltères en main, pose le pied entier sur la marche.', 'Pousse sur le talon pour monter : hanche et genou en extension complète.', 'Redescends lentement, pied arrière en premier.'],
    cues: 'Ne t\'aide pas de la jambe arrière : tout doit venir de la jambe avant.',
    errors: ['Propulsion avec le pied arrière', 'Genou en valgus', 'Descente non contrôlée'],
    breath: 'Expire en montant, inspire en descendant.',
    easier: 'rear-lunge', harder: 'bulgarian-split', flag: null },

  { id: 'kb-swing', name: 'Kettlebell Swing', group: 'Jambes',
    muscles: ['Fessiers', 'Ischio-jambiers'], secondary: ['Lombaires', 'Trapèze'],
    level: 2, equip: 'Kettlebell',
    steps: ['Kettlebell entre les pieds, légèrement en avant.', 'Hinge (flexion de hanche) en laissant le KB passer entre les jambes.', 'Extension explosive de hanche — le KB monte par l\'inertie, pas les bras.', 'Laisse le KB redescendre en guidant la trajectoire.'],
    cues: 'Le power vient de la hanche, pas des épaules. Image : claquer les fesses ensemble à l\'extension.',
    errors: ['Squat au lieu du hinge', 'Bras qui tirent', 'Dos arrondi dans la phase basse'],
    breath: 'Expire fort au sommet (ventre dur), inspire en descendant.',
    easier: 'romanian-dl', harder: null, flag: null },

  { id: 'hip-thrust-db', name: 'Hip Thrust haltère', group: 'Jambes',
    muscles: ['Fessiers', 'Ischio-jambiers'], secondary: ['Lombaires'],
    level: 2, equip: 'Haltères + banc',
    steps: ['Épaules posées sur le bord d\'un banc, haltère sur les hanches.', 'Pieds à largeur d\'épaules, à plat.', 'Monte les hanches jusqu\'à l\'horizontale en contractant les fessiers.', 'Redescends sans poser les fesses au sol.'],
    cues: 'Au sommet : tibia vertical, hanches en extension complète, fessiers maximalement contractés.',
    errors: ['Lombaires hyperétendus au sommet', 'Pieds trop proches du banc', 'Pas de bascule du bassin'],
    breath: 'Expire en montant, inspire en descendant.',
    easier: 'glute-bridge', harder: null, flag: null },

  { id: 'glute-bridge', name: 'Pont fessier', group: 'Jambes',
    muscles: ['Fessiers'], secondary: ['Ischio-jambiers', 'Lombaires'],
    level: 1, equip: 'Poids du corps',
    steps: ['Allongé sur le dos, genoux fléchis à ~90°, pieds à plat.', 'Monte le bassin jusqu\'à l\'horizontale en contractant les fessiers.', 'Tiens 1 sec au sommet, redescends lentement.'],
    cues: 'Serre les fessiers avant même de décoller le bassin — ça préactive les fibres profondes.',
    errors: ['Extension des lombaires (cambrure exagérée)', 'Talons décollés', 'Genoux qui tombent en dehors'],
    breath: 'Expire en montant.',
    easier: null, harder: 'hip-thrust-db', flag: null },

  { id: 'lateral-lunge', name: 'Fente latérale', group: 'Jambes',
    muscles: ['Quadriceps', 'Fessiers', 'Adducteurs'], secondary: ['Ischio-jambiers'],
    level: 2, equip: 'Poids du corps ou haltère',
    steps: ['Pieds serrés, debout.', 'Fais un grand pas sur le côté, plie le genou de la jambe d\'appui.', 'La jambe opposée reste tendue, le pied à plat.', 'Pousse sur le talon pour revenir.'],
    cues: 'Garde le tronc droit — ne laisse pas l\'épaule tomber vers la jambe d\'appui.',
    errors: ['Genou devant les orteils', 'Talon décollé', 'Flexion de tronc excessive'],
    breath: 'Expire en poussant pour revenir.',
    easier: 'rear-lunge', harder: 'bulgarian-split', flag: null },

  // ==============================
  // DOS — extensions
  // ==============================
  { id: 'pullup-supine', name: 'Tractions supination (biceps)', group: 'Dos',
    muscles: ['Biceps', 'Grand dorsal'], secondary: ['Avant-bras', 'Rhomboïdes'],
    level: 3, equip: 'Barre de traction',
    steps: ['Prise supination (paumes vers toi), mains à largeur d\'épaules.', 'Bras tendus, départ mort.', 'Tire en amenant le menton au-dessus de la barre.', 'Contrôle la descente.'],
    cues: 'Plus de biceps que les tractions pronation — utile pour varier le stimulus.',
    errors: ['Élan du corps', 'Pas d\'extension complète en bas', 'Coudes qui s\'écartent'],
    breath: 'Expire en tirant, inspire en descendant.',
    easier: 'inverted-row', harder: 'pullup-weighted', flag: null },

  { id: 'pullup-weighted', name: 'Tractions lestées', group: 'Dos',
    muscles: ['Grand dorsal', 'Biceps', 'Rhomboïdes'], secondary: ['Infraspinatus', 'Teres major'],
    level: 3, equip: 'Barre de traction + lest (haltère entre les jambes)',
    steps: ['Haltère tenu entre les chevilles ou ceinture de lest.', 'Même technique que les tractions standard.', 'Tempo lent impératif avec charge additionnelle.'],
    cues: 'Ajoute du lest seulement si tu fais 10+ reps propres sans lest. La forme prime.',
    errors: ['Balancement avec le lest', 'Descente rapide', 'Omoplates non rétractées'],
    breath: 'Expire en tirant.',
    easier: 'pullup-neutral', harder: null, flag: null },

  { id: 'band-row', name: 'Rowing élastique', group: 'Dos',
    muscles: ['Rhomboïdes', 'Grand dorsal', 'Biceps'], secondary: ['Trapèze moyen', 'Deltoïde postérieur'],
    level: 1, equip: 'Élastiques',
    steps: ['Fixe l\'élastique à hauteur de hanche (barre, porte).', 'Assis ou debout, bras tendus en avant.', 'Tire les coudes vers les hanches, omoplates vers la colonne.', 'Retour contrôlé.'],
    cues: 'Fin du mouvement : imagine que tu veux glisser tes omoplates vers tes fesses.',
    errors: ['Élan du tronc', 'Coudes écartés (>45°)', 'Aller trop vite'],
    breath: 'Expire en tirant, inspire en relâchant.',
    easier: null, harder: 'db-row', flag: null },

  { id: 'face-pull-band', name: 'Face Pull élastique', group: 'Dos',
    muscles: ['Deltoïde postérieur', 'Trapèze', 'Infraspinatus'], secondary: ['Rhomboïdes'],
    level: 1, equip: 'Élastiques',
    steps: ['Élastique fixé à hauteur de visage.', 'Tire vers ton visage, coudes hauts et vers l\'extérieur.', 'Rotation externe des épaules au point final — mains de chaque côté des oreilles.', 'Retour lent.'],
    cues: 'INCONTOURNABLE pour la santé des épaules — rétablit l\'équilibre antérieur/postérieur.',
    errors: ['Coudes qui descendent', 'Pas de rotation externe finale', 'Charge trop lourde'],
    breath: 'Expire en tirant, inspire en relâchant.',
    easier: null, harder: null, flag: null },

  { id: 'ring-row', name: 'Rowing sur anneaux', group: 'Dos',
    muscles: ['Grand dorsal', 'Rhomboïdes', 'Biceps'], secondary: ['Gainage'],
    level: 2, equip: 'Anneaux de gym',
    steps: ['Anneaux à hauteur de hanches, corps incliné sous les anneaux.', 'Bras tendus, corps en planche inversée.', 'Tire les anneaux vers le sternum en gardant le corps rigide.', 'Retour contrôlé.'],
    cues: 'Plus tu es horizontal, plus c\'est difficile. Régule la difficulté avec l\'angle de ton corps.',
    errors: ['Hanches qui tombent', 'Coudes écartés', 'Pas d\'extension complète'],
    breath: 'Expire en tirant.',
    easier: 'band-row', harder: 'pullup-neutral', flag: null },

  // ==============================
  // POUSSÉE — extensions
  // ==============================
  { id: 'pike-pushup', name: 'Pompes en Pike', group: 'Poussée',
    muscles: ['Deltoïde antérieur', 'Triceps'], secondary: ['Trapèze', 'Pectoraux'],
    level: 2, equip: 'Poids du corps',
    steps: ['Position pompes, monte les hanches pour former un V inversé.', 'Plie les coudes pour amener la tête vers le sol, entre les mains.', 'Pousse pour revenir.'],
    cues: 'Plus les hanches sont hautes, plus c\'est ciblé sur les épaules (vertical push progressif).',
    errors: ['Hanches trop basses (redevient une pompe normale)', 'Coudes qui s\'écartent', 'Tête relevée'],
    breath: 'Expire en poussant.',
    easier: 'incline-pushup', harder: 'handstand-pushup', flag: null },

  { id: 'handstand-pushup', name: 'Pompe en équilibre (handstand)', group: 'Poussée',
    muscles: ['Deltoïde', 'Triceps'], secondary: ['Trapèze', 'Gainage'],
    level: 3, equip: 'Poids du corps + mur',
    steps: ['Mains à 20 cm du mur, monte en appui renversé dos au mur.', 'Plie les coudes lentement : tête vers le sol.', 'Pousse pour revenir — coudes à 45° max vers l\'extérieur.'],
    cues: 'Commence par des négatifs (descente lente seulement) si tu ne peux pas encore monter.',
    errors: ['Dos cambré contre le mur', 'Coudes trop écartés', 'Descente non contrôlée'],
    breath: 'Inspire en descendant, expire en poussant.',
    easier: 'pike-pushup', harder: null, flag: null },

  { id: 'db-press', name: 'Développé haltères couché', group: 'Poussée',
    muscles: ['Pectoraux', 'Deltoïde antérieur', 'Triceps'], secondary: ['Serratus anterior'],
    level: 2, equip: 'Haltères + banc',
    steps: ['Allongé sur le banc, haltères au niveau des pectoraux, coudes à 45°.', 'Pousse les haltères vers le haut en les rapprochant légèrement au sommet.', 'Descends lentement jusqu\'à étirement des pectoraux.'],
    cues: 'Image mentale : essaie d\'écraser les deux haltères l\'un contre l\'autre — ça maximise la contraction pectorale.',
    errors: ['Coudes à 90° (risque épaule)', 'Omoplates non rétractées', 'Rebond en bas'],
    breath: 'Inspire en descendant, expire en poussant.',
    easier: 'incline-pushup', harder: null, flag: null },

  { id: 'db-shoulder-press', name: 'Développé épaules haltères', group: 'Poussée',
    muscles: ['Deltoïde', 'Triceps'], secondary: ['Trapèze supérieur'],
    level: 2, equip: 'Haltères',
    steps: ['Assis ou debout, haltères aux oreilles, coudes à 90°.', 'Pousse vers le haut jusqu\'à extension presque complète (pas de verrouillage dur).', 'Descends lentement, contrôlé.'],
    cues: 'ATTENTION si antécédent clavicule : utilise la variante neutre (paumes face à face) qui réduit la tension sur l\'articulation AC.',
    errors: ['Dos cambré (poussée lombaire)', 'Coudes en avant (perd l\'engagement deltoides)', 'Montée trop rapide'],
    breath: 'Expire en poussant.',
    easier: 'pike-pushup', harder: null, flag: 'clavicule' },

  { id: 'db-fly', name: 'Écarté haltères (fly)', group: 'Poussée',
    muscles: ['Pectoraux'], secondary: ['Deltoïde antérieur', 'Biceps (long)'],
    level: 2, equip: 'Haltères + banc ou sol',
    steps: ['Allongé, haltères tendus au-dessus, légèrement fléchis.', 'Ouvre les bras en arc de cercle jusqu\'à étirement des pectoraux (coudes ~160°).', 'Referme en contractant les pectoraux — pas de coup d\'épaule.'],
    cues: 'Imagine que tu entoures un grand arbre. L\'angle des coudes reste constant tout au long.',
    errors: ['Coudes trop fléchis (redevient un développé)', 'Descente trop profonde (hyperextension épaule)', 'Prise trop large'],
    breath: 'Inspire en ouvrant, expire en fermant.',
    easier: 'incline-pushup', harder: null, flag: null },

  { id: 'band-pushdown', name: 'Pushdown triceps élastique', group: 'Poussée',
    muscles: ['Triceps'], secondary: ['Avant-bras'],
    level: 1, equip: 'Élastiques',
    steps: ['Élastique fixé en hauteur (barre de traction, porte).', 'Coudes collés aux côtes, avant-bras à 90°.', 'Étends les bras vers le bas jusqu\'à extension complète.', 'Retour lent.'],
    cues: 'Les coudes sont le pivot — ils ne bougent PAS. Seuls les avant-bras se déplacent.',
    errors: ['Coudes qui s\'écartent', 'Pencher en avant pour aider', 'Rebond en bas'],
    breath: 'Expire en poussant vers le bas.',
    easier: null, harder: 'dips-partial', flag: null },

  // ==============================
  // BRAS — extensions
  // ==============================
  { id: 'hammer-curl', name: 'Curl marteau (hammer)', group: 'Bras',
    muscles: ['Biceps brachial', 'Brachioradialis'], secondary: ['Avant-bras'],
    level: 1, equip: 'Haltères',
    steps: ['Debout, haltères en prise neutre (pouce vers le haut).', 'Fléchis les coudes en gardant les coudes collés au corps.', 'Descends lentement.'],
    cues: 'La prise neutre cible mieux le brachioradialis — complète bien les curls classiques.',
    errors: ['Élan du tronc', 'Coudes qui avancent', 'Descente trop rapide'],
    breath: 'Expire en montant.',
    easier: null, harder: null, flag: null },



  { id: 'overhead-tricep', name: 'Extension triceps au-dessus tête', group: 'Bras',
    muscles: ['Triceps (chef long)'], secondary: ['Épaules'],
    level: 2, equip: 'Haltère',
    steps: ['Debout, un haltère tenu à deux mains au-dessus de la tête.', 'Plie les coudes pour descendre le poids derrière la tête.', 'Étends les coudes pour revenir.'],
    cues: 'Seul mouvement qui étire le chef long du triceps — indispensable pour une croissance complète.',
    errors: ['Coudes qui s\'écartent', 'Élan avec le tronc', 'Amplitude incomplète'],
    breath: 'Inspire en descendant, expire en montant.',
    easier: 'band-pushdown', harder: null, flag: null },

  { id: 'band-curl', name: 'Curl élastique', group: 'Bras',
    muscles: ['Biceps', 'Brachialis'], secondary: ['Avant-bras'],
    level: 1, equip: 'Élastiques',
    steps: ['Pose l\'élastique sous les pieds.', 'Prise supination, coudes collés au corps.', 'Fléchis les coudes jusqu\'en haut.', 'Retour lent — l\'élastique oppose plus de résistance en haut qu\'en bas.'],
    cues: 'La résistance croissante de l\'élastique correspond bien au profil de force du biceps.',
    errors: ['Coudes qui avancent', 'Relâchement en descente', 'Élan'],
    breath: 'Expire en fléchissant.',
    easier: null, harder: 'db-curl', flag: null },

  // ==============================
  // ABDOS — extensions
  // ==============================
  { id: 'dead-bug', name: 'Dead Bug', group: 'Abdos',
    muscles: ['Transverse', 'Obliques'], secondary: ['Stabilisateurs lombaires'],
    level: 1, equip: 'Poids du corps',
    steps: ['Allongé sur le dos, bras vers le plafond, hanches et genoux à 90°.', 'Bascule le bassin pour plaquer le bas du dos au sol.', 'Étends simultanément le bras droit et la jambe gauche vers l\'horizontale.', 'Reviens et alterne.'],
    cues: 'Le bas du dos doit rester en contact avec le sol à tout moment — c\'est le critère de réussite.',
    errors: ['Dos qui se décolle', 'Apnée', 'Mouvement trop rapide'],
    breath: 'Expire lentement pendant l\'extension.',
    easier: null, harder: 'hollow', flag: null },



  { id: 'ab-wheel', name: 'Ab Wheel (roue abdominale)', group: 'Abdos',
    muscles: ['Transverse', 'Grand droit', 'Obliques'], secondary: ['Grand dorsal', 'Triceps'],
    level: 3, equip: 'Roue abdominale',
    steps: ['À genoux, mains sur la roue.', 'Déroule lentement en tendant les bras, dos neutre, hanches en avant.', 'Va aussi loin que tu peux sans perdre la position neutre du dos.', 'Ramène en contractant les abdos.'],
    cues: 'C\'est l\'un des meilleurs exercices de gainage dynamique qui existe. Commence en amplitude partielle.',
    errors: ['Dos qui s\'affaisse à mi-chemin', 'Hanches trop hautes (fessiers compensent)', 'Bras qui font tout le travail'],
    breath: 'Expire en revenant.',
    easier: 'hollow', harder: null, flag: null },

  { id: 'bicycle-crunch', name: 'Bicycle Crunch', group: 'Abdos',
    muscles: ['Obliques', 'Grand droit'], secondary: ['Psoas'],
    level: 2, equip: 'Poids du corps',
    steps: ['Allongé sur le dos, mains derrière la nuque, genoux à 90°.', 'Amène le coude droit vers le genou gauche en tendant la jambe droite.', 'Alterne de façon fluide et contrôlée.'],
    cues: 'La rotation vient du torse, pas du coude. Menton décollé du sternum — espace pour un poing.',
    errors: ['Tirer sur le cou', 'Mouvement trop rapide (balistique)', 'Rotation insuffisante'],
    breath: 'Expire à chaque rotation.',
    easier: 'leg-raise', harder: null, flag: null },

  { id: 'hanging-knee-raise', name: 'Relevé de genoux suspendu', group: 'Abdos',
    muscles: ['Psoas-iliaque', 'Grand droit', 'Obliques'], secondary: ['Avant-bras', 'Gainage'],
    level: 2, equip: 'Barre de traction',
    steps: ['Suspendu à la barre, bras tendus.', 'Bascule le bassin vers l\'arrière (rétroversion) pour activer les abdos.', 'Remonte les genoux vers la poitrine en contrôlant.', 'Descends lentement — ne balance pas.'],
    cues: 'La rétroversion du bassin est la clé : sans elle, le psoas fait tout le travail.',
    errors: ['Élan', 'Bassin non rétroversé', 'Bras fléchis (perd la suspension)'],
    breath: 'Expire en montant.',
    easier: 'leg-raise', harder: 'toes-to-bar', flag: null },

  { id: 'toes-to-bar', name: 'Toes-to-Bar', group: 'Abdos',
    muscles: ['Grand droit', 'Psoas-iliaque', 'Obliques'], secondary: ['Grand dorsal', 'Avant-bras'],
    level: 3, equip: 'Barre de traction',
    steps: ['Suspendu à la barre, corps en creux (hollow).', 'Depuis la position creuse, bascule le bassin et remonte les jambes tendues vers la barre.', 'Contrôle la descente.'],
    cues: 'Le swing est une technique (kipping) — mais pour le travail abdominal, la version stricte sans élan est bien supérieure.',
    errors: ['Élan excessif', 'Jambes fléchies', 'Pas de rétroversion initiale'],
    breath: 'Expire en montant.',
    easier: 'hanging-knee-raise', harder: null, flag: null },

  // ==============================
  // CARDIO / CONDITIONING
  // ==============================
  { id: 'burpee', name: 'Burpee', group: 'Cardio',
    muscles: ['Corps entier'], secondary: ['Cardio-vasculaire'],
    level: 2, equip: 'Poids du corps',
    steps: ['Debout, descends en accroupi, pose les mains au sol.', 'Saute les pieds en arrière en position de pompe.', 'Pompe optionnelle.', 'Saute les pieds vers les mains, puis saute en l\'air bras levés.'],
    cues: 'Maintiens un tempo constant plutôt que de partir vite et finir épuisé. RPE 7-8 sur la durée.',
    errors: ['Dos affaissé en position pompe', 'Atterrissage pieds joints (genoux)', 'Rythme non maintenu'],
    breath: 'Expire au saut en l\'air, inspire en descendant.',
    easier: null, harder: null, flag: null },

  { id: 'mountain-climber', name: 'Grimpeur (Mountain Climber)', group: 'Cardio',
    muscles: ['Abdominaux', 'Épaules', 'Fléchisseurs de hanche'], secondary: ['Corps entier'],
    level: 1, equip: 'Poids du corps',
    steps: ['Position planche haute (pompe).', 'Ramène alternativement les genoux vers la poitrine, en courant.', 'Garde le bassin stable — ne le lève pas.'],
    cues: 'Image : tu cours à plat ventre. Le bassin est fixe — seules les jambes bougent.',
    errors: ['Bassin en l\'air', 'Épaules trop en avant des mains', 'Lent (perd l\'aspect cardio)'],
    breath: 'Respiration rythmique continue.',
    easier: null, harder: 'burpee', flag: null },

  { id: 'jump-rope', name: 'Corde à sauter', group: 'Cardio',
    muscles: ['Mollets', 'Épaules'], secondary: ['Cardio-vasculaire', 'Coordination'],
    level: 1, equip: 'Corde à sauter',
    steps: ['Poignées de corde au niveau des hanches, coudes légèrement fléchis.', 'Sauts sur place, 2-3 cm du sol seulement.', 'Rotation des poignets — pas des bras entiers.'],
    cues: 'Les sauts très bas économisent l\'énergie et réduisent les impacts. Commence par 30 sec, repose 30 sec.',
    errors: ['Bras qui font la rotation au lieu des poignets', 'Sauts trop hauts', 'Atterrissage talon en premier'],
    breath: 'Respiration nasale tant que possible.',
    easier: 'mountain-climber', harder: null, flag: null },

  // ==============================
  // ÉPAULES — nouveau groupe
  // ==============================
  { id: 'lateral-raise', name: 'Élévations latérales haltères', group: 'Épaules',
    muscles: ['Deltoïde moyen'], secondary: ['Trapèze supérieur'],
    level: 1, equip: 'Haltères',
    steps: ['Debout, haltères le long du corps, légère flexion des coudes.', 'Lève les bras sur les côtés jusqu\'à l\'horizontale.', 'Contrôle la descente en 2 s.'],
    cues: 'Imagine verser une carafe à l\'horizontale (pouce légèrement vers le bas). Garde les coudes au-dessus des poignets.',
    errors: ['Monter trop haut (au-dessus de l\'épaule = impingement)', 'Élan du buste', 'Poids trop lourd, shrug au lieu de raise'],
    breath: 'Expire en montant.',
    easier: null, harder: null, flag: null },

  { id: 'rear-delt-fly', name: 'Oiseau (rear delt fly)', group: 'Épaules',
    muscles: ['Deltoïde postérieur'], secondary: ['Rhomboïdes', 'Trapèze moyen'],
    level: 1, equip: 'Haltères',
    steps: ['Buste penché à 45-60°, haltères sous les épaules.', 'Ouvre les bras en arc de cercle, coudes légèrement fléchis.', 'Serre les omoplates en haut 1 s, redescends contrôlé.'],
    cues: 'Le mouvement miroir du fly pectoral. Indispensable pour l\'équilibre antérieur/postérieur de l\'épaule.',
    errors: ['Monter les épaules', 'Élan du buste', 'Poids trop lourd (c\'est un petit muscle)'],
    breath: 'Expire en ouvrant.',
    easier: 'face-pull-band', harder: null, flag: null },

  { id: 'band-pull-apart', name: 'Pull-apart élastique', group: 'Épaules',
    muscles: ['Deltoïde postérieur', 'Rhomboïdes'], secondary: ['Trapèze', 'Infraspinatus'],
    level: 1, equip: 'Élastiques',
    steps: ['Élastique devant toi, bras tendus à hauteur d\'épaules.', 'Écarte les mains en tirant l\'élastique vers ta poitrine.', 'Serre les omoplates, retour lent.'],
    cues: 'Excellent échauffement et travail de posture. 2-3 séries de 15 reps avant chaque séance haut du corps.',
    errors: ['Plier les coudes', 'Mouvement trop rapide', 'Épaules haussées'],
    breath: 'Expire en écartant.',
    easier: null, harder: 'rear-delt-fly', flag: null },

  { id: 'y-raise', name: 'Y-Raise (prone ou debout)', group: 'Épaules',
    muscles: ['Trapèze inférieur', 'Deltoïde postérieur'], secondary: ['Serratus anterior'],
    level: 1, equip: 'Poids du corps ou haltères légers',
    steps: ['Allongé face au sol ou buste penché.', 'Lève les bras en formant un Y, pouces vers le haut.', 'Tiens 2 s en haut, redescends.'],
    cues: 'Renforce les stabilisateurs de l\'omoplate — idéal en rehab épaule et en prévention.',
    errors: ['Monter trop haut (hyperextension)', 'Compensation lombaire'],
    breath: 'Expire en montant.',
    easier: null, harder: null, flag: null },

  // ==============================
  // JAMBES — compléments
  // ==============================
  { id: 'nordic-curl', name: 'Nordic curl (négatif)', group: 'Jambes',
    muscles: ['Ischio-jambiers'], secondary: ['Fessiers', 'Mollets'],
    level: 3, equip: 'Poids du corps + point d\'ancrage',
    steps: ['À genoux, chevilles bloquées (sous un meuble lourd, partenaire).', 'Descends le buste vers le sol le plus lentement possible.', 'Rattrape-toi avec les mains, pousse pour remonter.'],
    cues: 'L\'exercice n°1 de prévention des blessures aux ischio-jambiers. La descente lente est tout le travail.',
    errors: ['Casser à la hanche au lieu de descendre droit', 'Descente trop rapide', 'Forcer la remontée au lieu de s\'aider des mains'],
    breath: 'Inspire en haut, souffle pendant la descente.',
    easier: 'romanian-dl', harder: null, flag: null },

  { id: 'pistol-squat', name: 'Pistol squat (assisté)', group: 'Jambes',
    muscles: ['Quadriceps', 'Fessiers'], secondary: ['Équilibre', 'Mollets'],
    level: 3, equip: 'Poids du corps + support',
    steps: ['Debout sur une jambe, l\'autre tendue devant.', 'Descends en squat complet sur une jambe, mains en appui sur un support.', 'Remonte en poussant dans le talon.'],
    cues: 'Commence avec un TRX ou une porte comme support. Retire l\'aide progressivement.',
    errors: ['Genou qui rentre', 'Talon qui décolle', 'Descendre trop vite'],
    breath: 'Expire en remontant.',
    easier: 'bulgarian-split', harder: null, flag: null },

  { id: 'frog-pump', name: 'Frog pump', group: 'Jambes',
    muscles: ['Fessiers'], secondary: ['Adducteurs'],
    level: 1, equip: 'Poids du corps',
    steps: ['Allongé, plantes de pieds jointes, genoux ouverts (position papillon).', 'Monte le bassin en serrant les fessiers.', 'Pause 1 s en haut, redescends sans poser.'],
    cues: 'Activation fessière maximale grâce à la rotation externe. Parfait en échauffement avant squat.',
    errors: ['Pousser avec les lombaires', 'Amplitude trop faible'],
    breath: 'Expire en montant.',
    easier: null, harder: 'glute-bridge', flag: null },

  // ==============================
  // GAINAGE / MOBILITÉ
  // ==============================
  { id: 'pallof-press', name: 'Pallof press (élastique)', group: 'Abdos',
    muscles: ['Obliques', 'Transverse'], secondary: ['Stabilisateurs de hanche'],
    level: 2, equip: 'Élastiques',
    steps: ['Élastique fixé à hauteur de sternum, sur le côté.', 'Tiens l\'élastique contre la poitrine, debout perpendiculaire à l\'ancrage.', 'Pousse les mains vers l\'avant en résistant à la rotation.', 'Tiens 2 s bras tendus, ramène.'],
    cues: 'L\'anti-rotation est la fonction n°1 du core dans la vie réelle et le sport. Cet exercice l\'entraîne directement.',
    errors: ['Laisser le buste tourner', 'Pieds trop serrés', 'Résistance trop faible pour sentir le travail'],
    breath: 'Expire en poussant.',
    easier: 'plank-side', harder: null, flag: null },

  { id: 'bear-crawl', name: 'Bear crawl (marche de l\'ours)', group: 'Abdos',
    muscles: ['Transverse', 'Épaules'], secondary: ['Quadriceps', 'Coordination'],
    level: 2, equip: 'Poids du corps',
    steps: ['Position quatre pattes, genoux décollés de 2 cm du sol.', 'Avance main droite + pied gauche, puis alterne.', 'Garde le dos plat et le bassin stable.'],
    cues: 'Le gainage dynamique ultime : chaque pas est un anti-rotation et un anti-extension simultanés.',
    errors: ['Bassin qui se balance', 'Genoux trop hauts', 'Aller trop vite'],
    breath: 'Respiration continue.',
    easier: 'plank', harder: null, flag: null },

  { id: 'bird-dog', name: 'Bird-dog', group: 'Abdos',
    muscles: ['Transverse', 'Multifidus'], secondary: ['Fessiers', 'Deltoïde'],
    level: 1, equip: 'Poids du corps',
    steps: ['À quatre pattes, dos plat.', 'Tends simultanément le bras droit et la jambe gauche.', 'Tiens 2 s, reviens, alterne.'],
    cues: 'Consigne : un verre d\'eau posé sur ton dos ne doit pas tomber. Zéro rotation du bassin.',
    errors: ['Rotation du bassin', 'Hyperextension lombaire', 'Mouvement trop rapide'],
    breath: 'Expire en tendant.',
    easier: null, harder: 'dead-bug', flag: null },

  // ==============================
  // BRAS — compléments
  // ==============================
  { id: 'diamond-pushup', name: 'Pompes diamant', group: 'Bras',
    muscles: ['Triceps', 'Pectoraux'], secondary: ['Épaules', 'Gainage'],
    level: 2, equip: 'Poids du corps', flag: 'clavicule',
    steps: ['Position pompe, mains rapprochées formant un losange (pouces et index se touchent).', 'Descends poitrine vers les mains, coudes le long du corps.', 'Pousse pour revenir.'],
    cues: 'L\'exercice de triceps au poids du corps le plus efficace, selon les études EMG.',
    errors: ['Coudes trop écartés', 'Amplitude réduite', 'Bassin qui tombe'],
    breath: 'Expire en poussant.',
    easier: 'kickback', harder: null, flag: 'clavicule' },

  { id: 'wrist-curl', name: 'Curl poignet (avant-bras)', group: 'Bras',
    muscles: ['Fléchisseurs du poignet'], secondary: ['Avant-bras'],
    level: 1, equip: 'Haltère',
    steps: ['Avant-bras posé sur la cuisse, poignet en dehors du genou.', 'Laisse l\'haltère descendre en ouvrant les doigts.', 'Referme et fléchis le poignet vers le haut.'],
    cues: 'Renforce le grip pour les tractions et le SDT. 2-3 séries en fin de séance suffisent.',
    errors: ['Avant-bras qui décolle', 'Mouvement trop rapide', 'Charge trop lourde'],
    breath: 'Respiration libre.',
    easier: null, harder: null, flag: null },

  // ==============================
  // CARDIO — compléments
  // ==============================
  { id: 'high-knees', name: 'Montées de genoux', group: 'Cardio',
    muscles: ['Fléchisseurs de hanche', 'Abdominaux'], secondary: ['Mollets', 'Cardio-vasculaire'],
    level: 1, equip: 'Poids du corps',
    steps: ['Debout, alterne les genoux montés au niveau de la hanche.', 'Reste sur la pointe des pieds, bras qui balancent.', 'Maintiens un rythme élevé.'],
    cues: 'Excellent pour l\'échauffement : monte la température en 60 secondes.',
    errors: ['Genoux pas assez hauts', 'Buste penché en arrière', 'Rythme irrégulier'],
    breath: 'Respiration rythmique.',
    easier: null, harder: 'burpee', flag: null },

  { id: 'plank-jack', name: 'Plank jack', group: 'Cardio',
    muscles: ['Abdominaux', 'Épaules'], secondary: ['Adducteurs', 'Cardio-vasculaire'],
    level: 2, equip: 'Poids du corps',
    steps: ['Position planche haute (pompe).', 'Saute les pieds écartés puis serrés, comme un jumping jack horizontal.', 'Garde le bassin stable.'],
    cues: 'Combine gainage et cardio. Le bassin doit rester fixe — c\'est la difficulté.',
    errors: ['Bassin qui monte et descend', 'Épaules trop en avant', 'Rythme trop lent'],
    breath: 'Respiration continue.',
    easier: 'mountain-climber', harder: 'burpee', flag: null }
];

window.EXLIB_GROUPS = ['Jambes', 'Dos', 'Poussée', 'Épaules', 'Bras', 'Abdos', 'Cardio'];

// Recherche d'une fiche par nom approximatif (liens programme → bibliothèque)
window.findExercise = function (name) {
  const norm = (s) => s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const n = norm(name);
  return window.EXLIB.find(e => n.includes(norm(e.name)) || norm(e.name).includes(n.split('(')[0].trim()))
    || window.EXLIB.find(e => norm(e.name).split(' ').some(w => w.length > 4 && n.includes(w)));
};
