// ============================================================
// RECOMP — Base de connaissances du coach
// Chaque entrée : id, cat, q (question type affichée),
// keys (mots-clés de reconnaissance, sans accents),
// a (réponse), rel (questions liées)
// ============================================================

window.KB = [
  // ===================== NUTRITION =====================
  { id: 'prot-jour', cat: 'Nutrition', q: 'Combien de protéines par jour ?',
    keys: ['proteine', 'combien', 'jour', 'gramme'],
    a: "En recomposition/perte de gras : 1,6 à 2,2 g par kg de poids de corps et par jour. C'est LA priorité nutritionnelle n°1 pour préserver le muscle en déficit.\n\nRépartis sur 3–4 prises d'au moins 25–30 g : c'est le seuil qui déclenche pleinement la synthèse protéique musculaire. Exemple à 80 kg : ~145 g/jour = 4 repas à ~36 g.",
    rel: ['whey-utile', 'prot-sources'] },
  { id: 'prot-sources', cat: 'Nutrition', q: 'Meilleures sources de protéines pas chères ?',
    keys: ['proteine', 'source', 'pas cher', 'budget', 'economique'],
    a: "Classement qualité/prix :\n1. Œufs (si pas allergique) et thon/sardines en boîte\n2. Poulet entier (cuisse moins chère que le filet)\n3. Fromage blanc, skyr, lait (≈10 g/100 g pour 1 €/kg)\n4. Lentilles, pois chiches, haricots (protéines + fibres + fer)\n5. Steak haché 5 % surgelé en lot\n\nLa whey reste imbattable au gramme de protéine (~2 ct/g) si tu compares honnêtement.",
    rel: ['whey-utile', 'budget-courses'] },
  { id: 'whey-utile', cat: 'Nutrition', q: 'La whey est-elle utile ?',
    keys: ['whey', 'proteine poudre', 'shaker', 'utile'],
    a: "La whey n'est pas magique : c'est juste de la protéine de lait filtrée, pratique et bon marché. Elle compte exactement comme du poulet dans ton total.\n\nUtile si : tu as du mal à atteindre tes protéines avec la nourriture, ou besoin d'une collation rapide post-séance. Inutile si ton total est déjà atteint. 1 dose = ~24 g de protéines pour ~80 kcal.",
    rel: ['prot-jour', 'supp-utiles'] },
  { id: 'glucides-soir', cat: 'Nutrition', q: 'Les glucides le soir font-ils grossir ?',
    keys: ['glucide', 'soir', 'grossir', 'feculents', 'nuit'],
    a: "Mythe. Ce qui détermine la prise ou perte de gras, c'est le bilan calorique sur 24 h–7 jours, pas l'heure des glucides.\n\nDes études montrent même que regrouper les glucides le soir peut améliorer la satiété et le sommeil chez certains. Si manger des féculents le soir t'aide à tenir ta journée : fais-le sans culpabiliser.",
    rel: ['deficit-cest-quoi', 'jeune-intermittent'] },
  { id: 'deficit-cest-quoi', cat: 'Nutrition', q: 'Comment fonctionne le déficit calorique ?',
    keys: ['deficit', 'calorie', 'fonctionne', 'perdre', 'gras', 'maigrir'],
    a: "Ton corps dépense de l'énergie en permanence (métabolisme de base + activité + digestion). Si tu manges moins que cette dépense, il puise la différence dans ses réserves : c'est le déficit.\n\n~7 700 kcal ≈ 1 kg de gras. Un déficit de 350 kcal/jour ≈ -0,3 kg/semaine : assez rapide pour voir des résultats, assez doux pour préserver muscle et énergie. Ton app calcule ça automatiquement.",
    rel: ['plateau-poids', 'perte-muscle'] },
  { id: 'jeune-intermittent', cat: 'Nutrition', q: 'Le jeûne intermittent, ça marche ?',
    keys: ['jeune', 'intermittent', 'fasting', '16/8'],
    a: "Le jeûne intermittent ne fait pas maigrir par magie : il fait maigrir s'il t'amène à manger moins au total. C'est un outil de gestion de la faim, pas un brûleur de graisse.\n\nAvantage : moins de repas à gérer, repas plus gros donc plus rassasiants. Inconvénient : difficile d'atteindre ses protéines en 2 repas, et l'entraînement à jeun peut baisser la performance. Si ça te simplifie la vie : OK. Sinon, aucun intérêt physiologique supérieur.",
    rel: ['deficit-cest-quoi', 'cardio-jeun'] },
  { id: 'plateau-poids', cat: 'Nutrition', q: 'Mon poids stagne, que faire ?',
    keys: ['stagne', 'plateau', 'poids', 'bloque', 'descend plus'],
    a: "D'abord : un plateau se confirme sur 2 semaines de moyennes hebdo, pas sur 3 jours (l'eau fluctue de ±1 kg).\n\nSi c'est un vrai plateau, dans l'ordre :\n1. +2 000 pas/jour pendant 1 semaine (le NEAT baisse souvent en déficit sans qu'on s'en rende compte)\n2. Vérifie tes portions : les grammages dérivent avec le temps\n3. Seulement ensuite : -100 kcal sur les glucides ou lipides\n\nNe coupe jamais brutalement : tu perdrais du muscle et de l'énergie d'entraînement.",
    rel: ['deficit-cest-quoi', 'pese-quand'] },
  { id: 'pese-quand', cat: 'Nutrition', q: 'Quand et comment se peser ?',
    keys: ['peser', 'balance', 'quand', 'pesee', 'matin'],
    a: "Le matin, à jeun, après être passé aux toilettes, sans vêtements — mêmes conditions chaque jour.\n\nMais surtout : juge la MOYENNE de la semaine, jamais un seul matin. Ton poids varie de ±1 kg avec l'eau, le sel, les glucides et le contenu digestif. Une pesée isolée ne veut rien dire ; la tendance sur 7–14 jours dit tout. L'app trace cette tendance dans Suivi.",
    rel: ['plateau-poids'] },
  { id: 'triche-repas', cat: 'Nutrition', q: 'Les cheat meals sont-ils permis ?',
    keys: ['cheat', 'triche', 'ecart', 'craquer', 'resto', 'pizza'],
    a: "Reformulons : aucun aliment ne « casse » ta progression. Un repas plaisir hebdomadaire de 1 200 kcal dans une semaine à -2 500 kcal de déficit laisse encore -1 300 kcal de déficit.\n\nLe vrai danger, c'est le schéma « j'ai craqué donc tout est foutu donc je finis le paquet ». Un écart = un repas, pas une journée, pas un week-end. Reprends normalement au repas suivant, sans compensation punitive.",
    rel: ['faim-soir', 'deficit-cest-quoi'] },
  { id: 'faim-soir', cat: 'Nutrition', q: "J'ai faim le soir, comment gérer ?",
    keys: ['faim', 'soir', 'grignote', 'fringale', 'envie'],
    a: "Stratégies prouvées :\n1. Garde des calories pour le soir : petit-déj léger ou déjeuner réduit si ta faim est nocturne\n2. Protéines + fibres au dîner (volume + satiété) : légumes à volonté, viande maigre\n3. Fromage blanc/skyr en dessert : caséine à digestion lente = satiété prolongée\n4. Vérifie ton sommeil : la privation augmente la ghréline (hormone de la faim) de ~15 %\n\nLa faim du soir est souvent aussi de l'ennui ou une habitude : un thé + brossage de dents marquent la « fermeture de cuisine ».",
    rel: ['triche-repas', 'sommeil-important'] },
  { id: 'budget-courses', cat: 'Nutrition', q: 'Manger sainement avec un petit budget ?',
    keys: ['budget', 'courses', 'cher', 'economiser', 'prix'],
    a: "Le trio gagnant : surgelés (légumes et viande, même nutrition, -40 %), conserves (thon, sardines, légumineuses), et féculents secs en vrac (riz, avoine, pâtes, lentilles).\n\nBatch cooking : cuisiner 2× par semaine en grosses quantités évite les achats impulsifs (le poste de dépense caché n°1). Les recettes marquées « Batch » dans l'app sont conçues pour ça. ~50 €/semaine est tout à fait tenable pour un sportif seul.",
    rel: ['batch-cooking', 'prot-sources'] },
  { id: 'batch-cooking', cat: 'Nutrition', q: 'Comment organiser le batch cooking ?',
    keys: ['batch', 'cooking', 'meal prep', 'preparer', 'avance', 'organiser'],
    a: "Méthode 90 minutes le dimanche :\n1. Lance le four (patates douces, poulet) ET deux casseroles (riz/lentilles, sauce tomate)\n2. Pendant la cuisson : découpe les crudités de la semaine\n3. Répartis en boîtes : 3–4 déjeuners + bases de dîners\n\nConservation frigo : 3–4 jours (viande cuite), 5 jours (légumineuses, riz refroidi vite). Congèle ce qui dépasse. Les recettes « Batch » de l'app indiquent les multiplications de quantités.",
    rel: ['budget-courses'] },
  { id: 'alcool', cat: 'Nutrition', q: "L'alcool impacte-t-il mes résultats ?",
    keys: ['alcool', 'biere', 'vin', 'soiree', 'boire'],
    a: "Trois mécanismes : 1) 7 kcal/g, quasi aussi calorique que le gras, sans satiété. 2) Pendant que ton foie traite l'alcool, la lipolyse (combustion des graisses) est mise en pause. 3) Au-delà de 2–3 verres, la synthèse protéique et le sommeil profond chutent (~-25 % de récupération).\n\nEn pratique : 1–2 verres occasionnels = impact négligeable. Soirée arrosée hebdomadaire = frein réel et mesurable. Choisis tes batailles.",
    rel: ['sommeil-important'] },
  { id: 'edulcorants', cat: 'Nutrition', q: 'Les édulcorants sont-ils dangereux ?',
    keys: ['edulcorant', 'aspartame', 'sucralose', 'light', 'zero', 'soda'],
    a: "L'état de la science : aux doses de consommation réelles, les édulcorants approuvés (aspartame, sucralose, stévia) n'ont pas montré d'effet nocif robuste chez l'humain, ni d'effet prouvé sur l'insuline.\n\nUn soda zéro pour remplacer un soda sucré, c'est ~140 kcal économisées : un excellent outil de transition en perte de gras. L'eau reste la référence, mais ne te prive pas d'un levier qui marche par peur infondée.",
    rel: ['faim-soir'] },
  { id: 'micros-importants', cat: 'Nutrition', q: 'Quels micronutriments surveiller ?',
    keys: ['vitamine', 'mineraux', 'micro', 'carence', 'surveiller'],
    a: "En déficit calorique, les carences fréquentes chez le sportif :\n• Fer (fatigue) → viande rouge 2×/sem, lentilles, sardines\n• Magnésium (crampes, sommeil) → oléagineux, chocolat noir, eaux riches\n• Oméga-3 (récupération, inflammation) → poissons gras 2×/sem\n• Vitamine D (force, immunité) → soleil + supplémentation d'octobre à avril (1 000–2 000 UI/j)\n• Calcium si peu de laitages\n\nLes fiches recettes de l'app affichent les micros notables de chaque plat.",
    rel: ['supp-utiles', 'omega3'] },

  // ===================== ENTRAÎNEMENT =====================
  { id: 'series-combien', cat: 'Entraînement', q: 'Combien de séries par muscle ?',
    keys: ['serie', 'combien', 'volume', 'muscle', 'semaine'],
    a: "La science converge vers 10–20 séries efficaces par groupe musculaire et par semaine pour l'hypertrophie. En déficit calorique, vise plutôt le bas de la fourchette (10–13) : la récupération est réduite.\n\nUne série « efficace » = arrêtée à 0–3 reps de l'échec (RIR 0–3). 4 séries molles valent moins qu'2 séries dures. Ton programme actuel est calibré dans cette zone.",
    rel: ['echec-musculaire', 'rpe-rir'] },
  { id: 'rpe-rir', cat: 'Entraînement', q: 'RPE et RIR, comment les utiliser ?',
    keys: ['rpe', 'rir', 'intensite', 'echelle', 'reserve'],
    a: "RPE = effort perçu de 1 à 10. RIR = répétitions qu'il te restait « dans le réservoir ».\nRPE 10 = échec (RIR 0) · RPE 9 = 1 rep en réserve · RPE 8 = 2 reps · RPE 7 = 3 reps.\n\nPourquoi c'est puissant : la même charge est plus dure un jour de fatigue. Le RPE auto-régule — tu vises un effort, pas un chiffre absolu. Astuce de calibrage : si tu hésites entre 7 et 8, c'est un 7. Les débutants surestiment presque toujours leur RPE.",
    rel: ['echec-musculaire', 'progression-comment'] },
  { id: 'echec-musculaire', cat: 'Entraînement', q: "Faut-il aller à l'échec musculaire ?",
    keys: ['echec', 'failure', 'fond', 'jusqu au bout'],
    a: "Non, pas systématiquement. Les méta-analyses montrent des gains équivalents à 1–3 reps de l'échec, avec beaucoup moins de fatigue nerveuse et un meilleur volume total sur la semaine.\n\nL'échec a sa place : sur les exercices d'isolation (curls, mollets, élévations) en dernière série, où le risque est faible. Sur les exercices lourds polyarticulaires (squat, SDT), garde toujours 1–2 reps de marge : la technique se dégrade dangereusement à l'échec.",
    rel: ['rpe-rir', 'series-combien'] },
  { id: 'progression-comment', cat: 'Entraînement', q: 'Comment progresser avec un matériel limité ?',
    keys: ['progresser', 'progression', 'surcharge', 'materiel', 'limite', 'haltere', '16'],
    a: "Avec des haltères fixes de 16 kg, la surcharge progressive passe par d'autres leviers que la charge :\n1. Reps : +1 rep par série chaque semaine\n2. Tempo : descentes de 3 → 4 → 5 s (la tension prolongée = stimulus)\n3. Densité : mêmes séries, repos -15 s\n4. Unilatéral : le même haltère devient 2× plus dur sur une jambe/un bras\n5. Amplitude : déficit sur les fentes, étirement accentué au SDT\n\nQuand tu atteins 15+ reps faciles partout : passe à la variante unilatérale, pas à plus de reps.",
    rel: ['tempo-pourquoi', 'series-combien'] },
  { id: 'tempo-pourquoi', cat: 'Entraînement', q: 'À quoi sert le tempo (3010, etc.) ?',
    keys: ['tempo', '3010', 'lent', 'vitesse', 'excentrique'],
    a: "Lecture du code : 1er chiffre = descente (excentrique), 2e = pause en bas, 3e = montée (concentrique), 4e = pause en haut. « 3010 » = 3 s de descente, montée explosive.\n\nLa phase excentrique lente crée plus de micro-dommages et de tension mécanique — les deux moteurs de l'hypertrophie — à charge égale. C'est l'outil n°1 pour rendre 16 kg « lourds ». Bonus : elle protège les articulations en éliminant les rebonds.",
    rel: ['progression-comment'] },
  { id: 'fullbody-split', cat: 'Entraînement', q: 'Full body ou split, que choisir ?',
    keys: ['full body', 'split', 'half', 'repartition', 'organisation'],
    a: "La fréquence optimale par muscle est de 2×/semaine minimum (la synthèse protéique post-séance retombe en 48–72 h).\n\n• 2–3 séances/sem → full body ou half body (ton programme actuel : haut/bas) : chaque muscle est touché 1–2×\n• 4–5 séances/sem → upper/lower ou push/pull/legs\n\nLe split « 1 muscle par jour » des magazines est sous-optimal pour un naturel : 1 seule stimulation hebdo par muscle.",
    rel: ['series-combien', 'frequence-muscle'] },
  { id: 'frequence-muscle', cat: 'Entraînement', q: "Combien de fois entraîner chaque muscle ?",
    keys: ['frequence', 'fois', 'semaine', 'muscle', 'souvent'],
    a: "2× par semaine minimum par groupe musculaire — c'est le consensus des méta-analyses récentes. À volume hebdomadaire égal, le répartir sur 2–3 séances bat la séance unique.\n\nRaison : la synthèse protéique musculaire reste élevée 48–72 h après une séance, puis retombe. La toucher 2× = deux pics anaboliques au lieu d'un.",
    rel: ['fullbody-split', 'series-combien'] },
  { id: 'cardio-ordre', cat: 'Entraînement', q: 'Cardio avant ou après la muscu ?',
    keys: ['cardio', 'avant', 'apres', 'ordre', 'course', 'velo'],
    a: "Règle simple : la priorité passe en premier. En recomposition, c'est la musculation (elle préserve le muscle) → cardio APRÈS ou un autre jour.\n\nLe cardio avant la muscu vide le glycogène et dégrade la qualité des séries lourdes (effet d'interférence). Idéal : muscu 3×/sem + marche quotidienne (7–10 k pas) + 1 cardio modéré optionnel les jours off.",
    rel: ['cardio-jeun', 'neat-pas'] },
  { id: 'cardio-jeun', cat: 'Entraînement', q: 'Le cardio à jeun brûle-t-il plus de gras ?',
    keys: ['cardio', 'jeun', 'jeune', 'matin', 'bruler'],
    a: "Pendant la séance, oui, tu oxydes un peu plus de lipides. Sur 24 h, le corps compense et le total brûlé est identique — les études contrôlées sont claires.\n\nFais ton cardio quand il te convient. À jeun si tu aimes ça et que l'intensité reste basse ; après un repas si tu veux de la performance. Le seul facteur qui compte : le faire régulièrement.",
    rel: ['cardio-ordre', 'jeune-intermittent'] },
  { id: 'neat-pas', cat: 'Entraînement', q: 'Pourquoi viser 8 000-10 000 pas ?',
    keys: ['pas', 'marche', 'neat', '10000', 'marcher'],
    a: "Le NEAT (dépense hors sport : marche, gestes du quotidien) représente souvent 300–800 kcal/jour — plus que ta séance de muscu (~250–350 kcal).\n\nEn déficit, le corps réduit inconsciemment le NEAT (tu bouges moins sans t'en rendre compte) : c'est la cause n°1 des plateaux. Un objectif de pas verrouille cette dépense. La marche ne fatigue pas, ne coupe pas l'appétit, ne gêne pas la récupération : c'est l'arme parfaite de la perte de gras.",
    rel: ['plateau-poids', 'cardio-ordre'] },
  { id: 'echauffement', cat: 'Entraînement', q: 'Comment bien s\'échauffer ?',
    keys: ['echauffement', 'chauffer', 'avant seance', 'ramp', 'preparer'],
    a: "Protocole RAMP en 6–8 min :\n1. Raise (2 min) : élever la température — jumping jacks, montées de genoux, corde imaginaire\n2. Activate (2 min) : réveiller les muscles du jour — pont fessier avant les jambes, rowing léger avant le dos\n3. Mobilize (2 min) : mobiliser les articulations sollicitées — cercles de hanches, rotations d'épaules\n4. Potentiate : 1–2 séries légères du premier exercice (50 % de l'effort cible)\n\nLes étirements statiques longs AVANT la force baissent la performance : garde-les pour après.",
    rel: ['etirements', 'douleur-quand-stop'] },
  { id: 'etirements', cat: 'Entraînement', q: 'Les étirements sont-ils utiles ?',
    keys: ['etirement', 'stretching', 'souplesse', 'etirer'],
    a: "Dissocions :\n• AVANT la séance : étirements statiques > 30 s = perte de force temporaire de 5–10 %. À éviter. Préfère des mouvements dynamiques.\n• APRÈS ou les jours off : utiles pour la mobilité et la détente, sans effet prouvé sur les courbatures.\n• La muscu en amplitude complète développe elle-même la souplesse (le SDT roumain étire les ischios mieux que la plupart des étirements).\n\nVerdict : optionnels, agréables, mais pas une assurance anti-blessure.",
    rel: ['echauffement', 'courbatures'] },
  { id: 'abdos-tous-jours', cat: 'Entraînement', q: 'Peut-on faire des abdos tous les jours ?',
    keys: ['abdos', 'tous les jours', 'quotidien', 'ventre'],
    a: "Tu peux, mais c'est inutile : les abdos sont un muscle comme les autres — ils ont besoin de surcharge ET de récupération. 2–3 séances/semaine bien chargées (planches longues, relevés stricts, crunchs lestés) battent 7 séances de demi-mesure.\n\nEt rappel essentiel : les abdos visibles sont une affaire de taux de gras (déficit calorique), pas de nombre de crunchs. On ne brûle pas localement le gras du ventre.",
    rel: ['gras-localise', 'series-combien'] },
  { id: 'gras-localise', cat: 'Entraînement', q: 'Peut-on perdre du gras localement ?',
    keys: ['localise', 'ventre', 'cibler', 'perdre', 'zone', 'poignees'],
    a: "Non — c'est l'un des mythes les plus tenaces du fitness. Faire des abdos ne brûle pas le gras du ventre ; les études le confirment depuis les années 80.\n\nLa lipolyse est systémique : le corps puise dans ses réserves selon ta génétique et tes hormones, dans un ordre que tu ne contrôles pas (souvent le ventre en dernier chez l'homme, les hanches chez la femme). La seule stratégie : déficit + muscu pour garder le muscle + patience.",
    rel: ['abdos-tous-jours', 'deficit-cest-quoi'] },
  { id: 'duree-resultats', cat: 'Entraînement', q: 'Quand verrai-je des résultats ?',
    keys: ['resultat', 'quand', 'combien temps', 'voir', 'visible'],
    a: "Calendrier réaliste en recomposition :\n• Semaine 2–3 : force en hausse, meilleure énergie, sommeil amélioré\n• Semaine 4–6 : premiers changements au miroir (toi seul les vois)\n• Semaine 8–12 : changements visibles par les proches, vêtements plus amples\n• Mois 6+ : transformation objective sur photos\n\nLes photos mensuelles (mêmes conditions) battent le miroir quotidien, qui ne voit jamais rien. La balance, le mètre et la barre de traction sont tes vrais juges.",
    rel: ['plateau-poids', 'motivation-baisse'] },

  // ===================== RÉCUPÉRATION =====================
  { id: 'sommeil-important', cat: 'Récupération', q: 'Le sommeil est-il si important ?',
    keys: ['sommeil', 'dormir', 'nuit', 'important', 'heure'],
    a: "C'est le facteur de récupération n°1, loin devant tout supplément. Une étude célèbre : à déficit calorique égal, le groupe dormant 5,5 h a perdu 55 % de muscle EN PLUS que le groupe à 8,5 h.\n\nMoins de 6 h : -10 à -30 % de force le lendemain, +15 % de ghréline (faim), cortisol élevé. Vise 7–9 h. Leviers : heure de coucher fixe, chambre fraîche (18–19 °C), écrans coupés 30 min avant, caféine stoppée après 14 h.",
    rel: ['surentrainement', 'cafeine'] },
  { id: 'courbatures', cat: 'Récupération', q: 'Les courbatures sont-elles bon signe ?',
    keys: ['courbature', 'mal', 'douleur', 'lendemain', 'signe'],
    a: "Les courbatures (DOMS) signalent un stimulus inhabituel, pas une séance efficace. Tu peux progresser sans courbatures, et avoir des courbatures sans progresser (descendre des escaliers en donne).\n\nElles diminuent naturellement avec la répétition (effet de séance répétée) — c'est normal et souhaitable. S'entraîner avec des courbatures légères : OK. Courbatures sévères qui altèrent le mouvement : attends 1 jour ou travaille un autre groupe.",
    rel: ['recuperation-combien', 'surentrainement'] },
  { id: 'recuperation-combien', cat: 'Récupération', q: 'Combien de repos entre deux séances ?',
    keys: ['repos', 'recuperation', 'entre', 'seance', 'jours'],
    a: "48 h pour un même groupe musculaire est la règle de base (le muscle se reconstruit en 24–72 h selon le volume).\n\nTon programme alterné A/B le gère naturellement : tu peux enchaîner A puis B le lendemain (groupes différents), mais espace deux séances A de 48 h+. Signaux que tu n'as pas assez récupéré : perfs en baisse, RPE anormalement haut à charge égale, sommeil dégradé.",
    rel: ['courbatures', 'surentrainement'] },
  { id: 'surentrainement', cat: 'Récupération', q: 'Comment reconnaître le surmenage ?',
    keys: ['surentrainement', 'surmenage', 'fatigue', 'epuise', 'crame'],
    a: "Avec 2–4 séances/semaine, le vrai surentraînement est rare — mais le « sous-récupération » (déficit + stress + sommeil court) est fréquent. Signaux :\n• Performances en baisse 2 séances de suite\n• Fréquence cardiaque au réveil +5–10 bpm\n• Sommeil agité malgré la fatigue, irritabilité\n• Motivation à zéro, appétit déréglé\n\nRéponse : 1 semaine de deload (volume -50 %), sommeil prioritaire, et remonte les calories au maintien quelques jours si besoin. Le coach surveille ces signaux dans tes données.",
    rel: ['deload-quoi', 'sommeil-important'] },
  { id: 'deload-quoi', cat: 'Récupération', q: "C'est quoi un deload ?",
    keys: ['deload', 'decharge', 'semaine legere', 'pause'],
    a: "Une semaine volontairement allégée : mêmes exercices, volume réduit de 40–50 % (moitié des séries), RPE plafonné à 6–7. Toutes les 4–6 semaines d'entraînement dur, ou dès que les signaux de fatigue s'accumulent.\n\nCe n'est pas une semaine perdue : la fatigue accumulée masque ta vraie force. Après un deload, les perfs bondissent presque toujours. Ton programme de 4 semaines peut se conclure par un deload avant le cycle suivant.",
    rel: ['surentrainement', 'recuperation-combien'] },

  // ===================== DOULEURS & SÉCURITÉ =====================
  { id: 'douleur-quand-stop', cat: 'Douleurs', q: 'Douleur : quand s\'arrêter ?',
    keys: ['douleur', 'arreter', 'stop', 'continuer', 'mal'],
    a: "La règle des 3/10 : une gêne ≤ 3/10 qui ne s'aggrave pas pendant l'effort est généralement tolérable. Au-delà, ou si elle augmente rep après rep : on arrête CET exercice aujourd'hui (pas forcément la séance).\n\nDistingue : douleur musculaire diffuse (brûlure, courbature) = souvent OK ; douleur articulaire précise, pointe, élancement = signal d'arrêt. Douleur qui persiste au repos ou > 7 jours → consulte un professionnel de santé. Je suis un coach, pas un médecin.",
    rel: ['douleur-epaule', 'douleur-genou', 'douleur-lombaire'] },
  { id: 'douleur-epaule', cat: 'Douleurs', q: 'Gêne à l\'épaule ou la clavicule ?',
    keys: ['epaule', 'clavicule', 'gene', 'douleur', 'coiffe'],
    a: "Protocole avec ton antécédent :\n1. Stoppe immédiatement toute poussée (dips, pompes) au moindre signal — remplace par pompes surélevées, plus le support est haut, moins ça contraint\n2. Les tirages (rowing, tractions prise neutre) restent généralement sûrs et même bénéfiques : ils renforcent les stabilisateurs\n3. Évite tout mouvement au-dessus de 90° d'élévation tant que la gêne existe\n4. Réintroduis progressivement : surélevé → genoux → sol → dips partiels, avec 2 semaines sans douleur entre chaque étape\n\nDouleur persistante au repos → professionnel de santé.",
    rel: ['douleur-quand-stop', 'dips-securite'] },
  { id: 'dips-securite', cat: 'Douleurs', q: 'Les dips sont-ils risqués pour moi ?',
    keys: ['dips', 'risque', 'securite', 'danger'],
    a: "Les dips sont l'exercice de poussée le plus exigeant pour l'épaule : en bas du mouvement, l'articulation est en extension + rotation sous charge complète du poids du corps.\n\nTon protocole conditionnel : buste quasi vertical, descente limitée à coudes 90°, tempo contrôlé 2 s. Trois signaux d'exclusion immédiate : pincement antérieur d'épaule, gêne claviculaire, craquement douloureux. Dans ce cas → pompes surélevées sans état d'âme. Aucun exercice ne vaut une rechute.",
    rel: ['douleur-epaule', 'douleur-quand-stop'] },
  { id: 'douleur-genou', cat: 'Douleurs', q: 'Douleur au genou en squat/fente ?',
    keys: ['genou', 'douleur', 'squat', 'fente', 'rotule'],
    a: "Checklist dans l'ordre :\n1. Technique : genoux dans l'axe des orteils (jamais en dedans), talons ancrés\n2. Amplitude : travaille dans la zone sans douleur, élargis progressivement\n3. Tempo : descentes 3–4 s, supprime tout rebond en bas\n4. Variante : fentes ARRIÈRE (moins de cisaillement que les fentes avant), box squat, ou hip thrust en attendant\n5. Renforce ce qui entoure : fessiers (pont, hip thrust) et mollets stabilisent le genou\n\nUne douleur sous/autour de la rotule qui persiste 2 semaines → consulte.",
    rel: ['douleur-quand-stop'] },
  { id: 'douleur-lombaire', cat: 'Douleurs', q: 'Le bas du dos tire pendant le SDT ?',
    keys: ['lombaire', 'bas du dos', 'dos', 'tire', 'sdt', 'souleve'],
    a: "Une fatigue lombaire diffuse après le SDT roumain est normale (les lombaires gainent en isométrie). Une douleur aiguë ou asymétrique ne l'est pas.\n\nCorrections :\n1. Filme-toi de profil : le dos doit rester neutre, pas arrondi en bas\n2. Réduis l'amplitude : descends seulement jusqu'où le dos reste plat\n3. Hanches EN ARRIÈRE, pas buste en avant : c'est une charnière\n4. Gaine avant chaque rep : inspire, ventre dur, puis descends\n5. Alterne avec le hip thrust (zéro contrainte lombaire) si besoin\n\nDouleur qui irradie dans la jambe → consulte rapidement.",
    rel: ['douleur-quand-stop'] },

  // ===================== SUPPLÉMENTS =====================
  { id: 'supp-utiles', cat: 'Suppléments', q: 'Quels suppléments valent le coup ?',
    keys: ['supplement', 'complement', 'utile', 'lequel', 'acheter'],
    a: "Hiérarchie selon les preuves scientifiques :\n1. Créatine monohydrate (3–5 g/j, tous les jours) : +5–10 % force, le supplément le plus étudié au monde\n2. Whey : pratique pour atteindre les protéines, pas magique\n3. Vitamine D (octobre→avril, 1 000–2 000 UI/j)\n4. Caféine pré-séance (3–6 mg/kg) : ergogène prouvé\n5. Oméga-3 si < 2 poissons gras/semaine\n\nTout le reste (BCAA, brûleurs, boosters, glutamine) : économise ton argent. Avec des protéines suffisantes, les BCAA sont littéralement redondants.",
    rel: ['creatine-comment', 'whey-utile', 'omega3'] },
  { id: 'creatine-comment', cat: 'Suppléments', q: 'Comment prendre la créatine ?',
    keys: ['creatine', 'prendre', 'dose', 'quand', 'charge'],
    a: "3–5 g par jour, TOUS les jours (entraînement ou pas), à n'importe quelle heure — seule la régularité compte, le timing est indifférent. La saturation musculaire prend ~3–4 semaines (la « phase de charge » à 20 g/j l'accélère mais est inutile).\n\nEffets attendus : +5–10 % de force, +1–2 kg sur la balance (eau intramusculaire, pas du gras — ne panique pas en voyant le poids monter). Forme : monohydrate basique, la moins chère, toutes les autres formes « avancées » sont du marketing. Bois normalement, aucun risque rénal démontré chez le sujet sain.",
    rel: ['supp-utiles'] },
  { id: 'cafeine', cat: 'Suppléments', q: 'La caféine avant la séance ?',
    keys: ['cafeine', 'cafe', 'booster', 'pre workout', 'energie'],
    a: "Le pré-workout le plus efficace et le moins cher : 3–6 mg/kg (soit 2–3 cafés serrés pour 80 kg), 45–60 min avant la séance. Effets prouvés : +force, +endurance, -perception de l'effort.\n\nGarde-fous : stop après 14 h si tu tiens à ton sommeil (demi-vie de 5–6 h), et la tolérance s'installe — réserve les grosses doses aux séances dures. Les poudres pré-workout du commerce vendent surtout… de la caféine à prix d'or avec des picotements (bêta-alanine).",
    rel: ['supp-utiles', 'sommeil-important'] },
  { id: 'omega3', cat: 'Suppléments', q: 'Les oméga-3, pour quoi faire ?',
    keys: ['omega', 'poisson', 'huile', 'epa', 'dha'],
    a: "Rôles documentés : modulation de l'inflammation, santé cardiovasculaire, et des données émergentes sur la préservation musculaire et la récupération.\n\nPriorité à l'alimentation : sardines, maquereau, saumon 2×/semaine couvrent les besoins (et les conserves de sardines sont imbattables en prix). En supplément si tu ne manges pas de poisson : 1–2 g EPA+DHA/jour, conservés au frigo.",
    rel: ['micros-importants', 'supp-utiles'] },

  // ===================== MENTAL & MOTIVATION =====================
  { id: 'motivation-baisse', cat: 'Mental', q: 'Je perds la motivation, que faire ?',
    keys: ['motivation', 'envie', 'flemme', 'demotive', 'abandon'],
    a: "La motivation est une émotion : elle fluctue par nature. Les gens qui « réussissent » ne sont pas plus motivés — ils s'appuient sur des systèmes :\n1. Règle des 2 exercices : engage-toi seulement sur les 2 premiers. 80 % du temps tu finiras la séance ; sinon, c'est quand même validé\n2. Même heure, mêmes jours : la décision disparaît, l'habitude décide\n3. Ne casse jamais la chaîne 2× de suite : rater 1 fois = humain, 2 fois = nouvelle habitude\n4. Regarde tes graphiques dans Suivi : la preuve visuelle de progression est le meilleur carburant connu",
    rel: ['regularite-importance', 'duree-resultats'] },
  { id: 'regularite-importance', cat: 'Mental', q: 'Régularité ou intensité ?',
    keys: ['regularite', 'constance', 'intensite', 'discipline'],
    a: "La régularité gagne, mathématiquement. Compare sur un an :\n• 2 séances/semaine moyennes, 50 semaines = 100 séances\n• 5 séances/semaine parfaites pendant 6 semaines, puis abandon = 30 séances\n\nLe corps s'adapte au stimulus RÉPÉTÉ. Un programme « moyen » suivi 6 mois bat le programme parfait suivi 6 semaines, dans 100 % des cas. C'est exactement pour ça que ton plan tient sur 2 séances : il est conçu pour être tenable, pas impressionnant.",
    rel: ['motivation-baisse'] },
  { id: 'stress-impact', cat: 'Mental', q: 'Le stress freine-t-il mes progrès ?',
    keys: ['stress', 'cortisol', 'travail', 'anxiete'],
    a: "Oui, par trois canaux mesurables : le cortisol chroniquement élevé favorise le stockage abdominal et freine la synthèse protéique ; le stress dégrade le sommeil (et donc tout le reste) ; et il pousse à l'alimentation émotionnelle.\n\nCe qui marche : l'entraînement lui-même (anxiolytique prouvé, à condition de ne pas en faire un stress de plus), la marche en extérieur, et 5 min de respiration lente (4 s inspire / 6 s expire) le soir. Les semaines très chargées, réduis le volume de 30 % plutôt que de sauter les séances : le mouvement protège.",
    rel: ['sommeil-important', 'motivation-baisse'] },
  { id: 'femmes-muscu', cat: 'Mental', q: 'La muscu rend-elle « massif » ?',
    keys: ['massif', 'gros', 'trop muscle', 'femme', 'volumineux'],
    a: "Impossible par accident. Construire du muscle visible demande des années d'entraînement structuré, un surplus calorique et une progression constante des charges — personne ne devient « trop musclé » sans le chercher activement pendant longtemps.\n\nEn recomposition (déficit + muscu), le résultat est un corps plus dense, plus dessiné et plus ferme, jamais plus volumineux. Les femmes, avec ~15× moins de testostérone, sont encore plus loin de ce « risque ».",
    rel: ['duree-resultats'] },
  { id: 'photo-suivi', cat: 'Mental', q: 'Comment bien suivre ma transformation ?',
    keys: ['photo', 'suivre', 'mesure', 'transformation', 'mensuration'],
    a: "Le tableau de bord complet, par fiabilité :\n1. Photos mensuelles : même lieu, même lumière, même heure, face/profil/dos\n2. Tour de taille au nombril (le meilleur proxy du gras viscéral) : 1×/semaine\n3. Moyenne hebdo du poids (déjà tracée dans Suivi)\n4. Performances : tes records dans l'app sont un marqueur direct de préservation musculaire\n\nLe miroir quotidien est le PIRE outil : le cerveau s'habitue et ne voit jamais le changement. Fais confiance aux données.",
    rel: ['pese-quand', 'duree-resultats'] },

  // ===================== TECHNIQUE SPÉCIFIQUE =====================
  { id: 'premiere-traction', cat: 'Technique', q: 'Comment obtenir ma première traction ?',
    keys: ['traction', 'premiere', 'reussir', 'arriver', 'pull up'],
    a: "Programme d'accès en 3 axes, 2–3×/semaine :\n1. Négatives lentes : monte avec une chaise, descends en 5 s. 3×5. C'est le constructeur principal\n2. Rowing inversé sous table : 3×10–12, renforce le tirage horizontal\n3. Suspension active : pends-toi bras tendus, omoplates basses, 3×20–30 s (grip + épaules)\n\nProgression typique : 4–8 semaines pour la première traction stricte si tu pars de 0. Teste 1 traction max chaque 2 semaines, jamais plus souvent.",
    rel: ['progression-comment'] },
  { id: 'grip-faible', cat: 'Technique', q: 'Ma prise lâche avant mes muscles ?',
    keys: ['grip', 'prise', 'avant bras', 'lache', 'tenir'],
    a: "Classique sur le SDT roumain et les tractions. Solutions :\n1. Suspension à la barre en fin de séance : 3× max secondes, le grip progresse vite\n2. Prise mixte ou crochet sur les derniers reps de SDT\n3. Sépare les exercices de grip : ne mets pas SDT et tractions dos à dos\n4. La magnésie (même liquide) change la vie si tes mains glissent\n\nÉvite les sangles pour l'instant : à ton niveau de charge, le grip doit progresser avec le reste.",
    rel: ['premiere-traction'] },
  { id: 'respiration-effort', cat: 'Technique', q: 'Comment respirer pendant l\'effort ?',
    keys: ['respirer', 'respiration', 'souffle', 'apnee'],
    a: "Règle générale : inspire pendant la phase facile (descente), expire pendant l'effort (montée). Exemple squat : inspire en haut, descends, expire en poussant.\n\nSur les charges lourdes, la manœuvre de Valsalva (bloquer l'air, ventre dur) stabilise la colonne — c'est naturel et sûr pour un sujet sain sur 1–3 reps. Sur le gainage : ne bloque JAMAIS, respiration continue. Si tu vois des étoiles : tu bloques trop longtemps.",
    rel: ['tempo-pourquoi'] }
];

// Catégories pour la navigation du chat
window.KB_CATS = ['Nutrition', 'Entraînement', 'Récupération', 'Douleurs', 'Suppléments', 'Mental', 'Technique'];
